# -*- coding: utf-8 -*-

"""File for holding a list of all attachments for weapons - primary and secondary."""

from enum import Enum

class Muzzles(Enum):
    # added for SVA 545 Assault Rifle
    NO_MODIFICATIONS = "NO MODIFICATIONS"
    SHADOWSTRIKE_SUPPRESSOR = "SHADOWSTRIKE SUPPRESSOR"
    VT7_SPIRITFIRE_SUPPRESSOR = "VT-7 SPIRITFIRE SUPPRESSOR"
    HMRES_MOD_SUPPRESSOR = "HMRES MOD SUPPRESSOR"
    MONOLITHIC_SUPPRESSOR = "MONOLITHIC SUPPRESSOR"
    SONIC_SUPPRESSOR = "SONIC SUPPRESSOR"
    COLOSSUS_SUPPRESSOR = "COLOSSUS SUPPRESSOR"
    BROADHEAD_3DP = "BROADHEAD-3DP"
    SILENTFIRE_XG6 = "SILENTFIRE XG6"
    ECHOLINE_GSX = "ECHOLINE GS-X"
    ZULU_60 = "ZULU-60"
    HARBINGER_D20 = "HARBINGER D20"
    ECHOLESS_80 = "ECHOLESS-80"
    FSS_COVERT_V = "FSS COVERT V"
    GAUGE_9_MONO = "GUAGE-9 MONO"
    ELR_BLACKFIRE_COMPENSATOR = "ELR BLACKFIRE COMPENSATOR"
    WRATHGUARD_COMPENSATOR = "WRATHGUARD COMPENSATOR"
    T4LR_SABER_COMPENSATOR = "T4LR SABER COMPENSATOR"
    EX01_MATCH_COMPENSATOR = "EX-01 MATCH COMPENSATOR"
    T51R_BILLETED_BRAKE = "T51R BILLETED BRAKE"
    PURIFIER_MUZZLE_BRAKE = "PURIFIER MUZZLE BRAKE"
    CASUS_BRAKE = "CASUS BRAKE"
    ENDLESS_30_COMPENSATOR = "ENDLESS 30 COMPENSATOR"
    JAK_BFB = "JAK BFB"
    RF_CROWN_50 = "RF CROWN 50"
    KOMODO_HEAVY = "KOMODO HEAVY"
    XTEN_PORTED_290 = "XTEN PORTED 290"
    FJX_FULCRUM_PRO = "FJX FULCRUM PRO"
    CRONEN_OP44 = "CRONEN OP44"
    FTAC_CASTLE_COMP = "FTAC CASTLE COMP"
    XTEN_HAVOC_90 = "XTEN HAVOC 90"
    SAKIN_TREAD_40 = "SAKIN TREAD-40"
    S37C_DL_BREACHER_DEVICE = "S-37C DL BREACHER DEVICE"
    C400_DOOR_KNOCKER = "C400 DOOR KNOCKER"
    JCZ_390_MUZZLE_DEVICE = "JCZ-390 MUZZLE DEVICE"
    L4R_FLASH_HIDER = "L4R FLASH HIDER"
    CORVUS_SLASH_GEN2 = "CORVUS SLASH GEN. 2"
    CRONEN_MAW_86 = "CRONEN MAW-86"
    DARK_KX30 = "DARK KX30"
    VLK_KOLOSS_FLASH_HIDER = "VLK KOLOSS FLASH HIDER"
    STER45_SKYFURY_COMPENSATOR = "STER45 SKYFURY COMPENSATOR"
    ZEHMN35_COMPENSATED_FLASH_HIDER = "ZEHMN35 COMPENSATED FLASH HIDER"

    # added for Kastov762 Assault Rifle
    VT7_SPIRITFIRE_SUPPRESSOR_L = "VT-7 SPIRITFIRE SUPPRESSOR L"
    HMRES_MOD_SUPPRESSOR_L = "HMRES MOD SUPPRESSOR L"
    COLOSSUS_SUPPRESSOR_L = "COLOSSUS SUPPRESSOR L"
    BRUEN_HARMONIC_SUPPRESSOR_L = "BRUENEN HARMONIC SUPPRESSOR L"
    HUSHER_65_SILENCER = "HUSHER-65 SILENCER"
    FR_TITAN_SILENCER = "FR TITAN SILENCER"
    POLOARFIRE_S = "POLARFIRE-S"
    ZLR_TALON_5 = "ZLR TALON 5"
    KASTOVIA_DX90 = "KASTOVIA DX90"
    CRONEN_SPDR = "CRONEN SP-DR"
    STER45_SKYFURY_COMPENSATOR_L = "STER45 SKYFURY COMPENSATOR L"
    ELR_BLACKFIRE_COMPENSATOR_L = "ELR BLACKFIRE COMPENSATOR L"
    T4LR_SABER_COMPENSATOR_L = "T4LR SABER COMPENSATOR L"
    EX01_MATCH_COMPENSATOR_L = "EX-01 MATCH COMPENSATOR L"
    T51R_BILLETED_BRAKE_L = "T51R BILLETED BRAKE L"
    PURIFIER_MUZZLE_BRAKE_L = "PURIFIER MUZZLE BRAKE L"
    CASUS_BRAKE_L = "CASUS BRAKE L"
    TEMPUS_GH50 = "TEMPUS GH50"
    TY_LR8 = "TY-LR8"
    LOCKSHOT_KT85 = "LOCKSHOT KT85"
    SA_LEVELER_55 = "SA LEVELER 55"
    BORE_490 = "BORE-490"
    S37C_DL_BREACHER_DEVICE_L = "S-37C DL BREACHER DEVICE L"
    GL_CLEAR_BREACH = "GL CLAER BREACH"
    TA_HUL_BREACH_KL = "TL HUL-BREACH KL"
    EIGHT_POINT_FLASH_HIDER = "EIGHT-POINT FLASH HIDER"
    TZL_90_V3 = "TZL-90 V3"
    CRONEN_DARK_KX30 = "CRONEN DARK KX30"
    MONOLITHIC_SUPPRESSOR_L = "MONOLITHIC SUPPRESSOR L"
    SONIC_SUPPRESSOR_L = "SONIC SUPPRESSOR L"
    WRATHGUARD_COMPENSATOR_L = "WRATHGUARD COMPENSATOR L"

    # added for FTAC RECON Battle Rifle
    NILSOUND_90 = "NILSOUND 90"
    FTAC_DREADNOUGHT = "FTAC DREADNOUGHT"
    FTAC_REAPER = "FTAC REAPER"
    BRUEN_AGENT_90 = "BRUEN AGENT 90"
    TALON_SIXTEEN = "TALON SIXTEEN"
    EXF_RELENTLESS_40 = "EXF RELENTLESS-40"
    BVM_338 = "BVM-338"
    CRONEN_DM338 = "CRONEN DM338"
    SHRED_CP90 = "SHRED CP90"
    XRK_KRAKEN = "XRK KRAKEN"
    TA_CG76 = "TA CG76"
    AP_390_FLASH_HIDER = "AP-390 FLASH HIDER"
    PORTED_DZ38 = "PORTED DZ38"
    DARK_KX50_FLASH_HIDER = "DARK KX50 FLASH HIDER"
    DEMON_HELIX_T7 = "DEMON HELIX T7"
    SHADOWSTRIKE_SUPPRESSOR_L = "SHADOWSTRIKE SUPPRESSOR L"

    # added for STIKER SMG
    SHADOWSTRIKE_SUPPRESSOR_S = "SHADOWSTRIKE SUPPRESSOR S"
    HMRES_MOD_SUPPRESSOR_S = "HMRES MOD SUPPRESSOR S"
    MONOLITHIC_SUPPRESSOR_S = "MONOLITHIC SUPPRESSOR S"
    COLOSSUS_SUPPRESSOR_S = "COLOSSUS SUPPRESSOR S"
    XTEN_RR_40 = "XTEN RP-40"
    FORGE_DX90_F = "FORGE DX90-F"
    SA_SCHALLDAMPFER_99 = "SA SCHALLDAMPFER 99"
    SINGUARD_MKV = "SINGUARD MKV"
    EXF_HUNTRESS_90 = "EXF HUNTRESS 90"
    XTEN_BLACK_KITE = "XTEN BLACK KITE"
    FSS_COVERT_IV = "FSS COVERT IV"
    STER45_SKYFURY_COMPENSATOR_S = "STER45 SKYFURY COMPENSATOR S"
    ELR_BLACKFIRE_COMPENSATOR_S = "ELR BLACKFIRE COMPENSATOR S"
    T4LR_SABER_COMPENSATOR_S = "T4LR SABER COMPENSATOR S"
    PURIFIER_MUZZLE_BRAKE_S = "PURIFIER MUZZLE BRAKE S"
    BRUEN_PENDULUM = "BRUEN PENDULUM"
    AVR_T90_COMP = "AVR-T90 COMP"
    LACERTA_COMPENSATOR = "LACERTA COMPENSATOR"
    XTEN_RAZOR_COMP = "XTEN_RAZOR_COMP"
    XRK_SANDSTORM = "XRK_SANDSTORM"
    BRUEN_CUBIC_COMP = "BRUEN CUBIC COMP"
    XRK_KNOCKOUT_BREACH = "XRK KNOCKOUT BREACH"
    TA_HUL_BREACH = "TL HUL-BREACH"
    SPIRAL_V3p5_FLASH_HIDER = "SPIRAL V3.5 FLASH HIDER"
    FOX_202_FLASH_HIDER = "FOX-202 FLASH HIDER"
    SONIC_SUPPRESSOR_S = "SONIC SUPPRESSOR S"
    WRATHGUARD_COMPENSATOR_S = "WRATHGUARD COMPENSATOR S"
    T51R_BILLETED_BRAKE_S = "T51R BILLETED BRAKE S"
    VP27_MINI_BRAKE_S = "VP27 MINI BRAKE S"
    S37C_DL_BREACHER_DEVICE_S = "S-37C DL BREACHER DEVICE S"

    # added for FENNEC SMG
    SHIKRA_SILENCER = "SHIKRA SILENCER"

    # added for LOCKWOOD 680 shotgun
    TECTONICA_SUPPRESSOR = "TECTONICA SUPPRESSOR"
    SA_SCHWEIGEN_DX = "SA SCHWEIGEN DX"
    SA_SCHWEIGEN_XS = "SA SCHWEIGEN XS"
    FTAC_TRIDENTCORE = "FTAC TRIDENTCORE"
    SA_MX_50 = "SA MX-50"
    DR_77_IRONHEAD_BRAKE = "DR-77 IRONHEAD BRAKE"
    SR70_TAQ_BRAKE = "SR70 TAQ BRAKE"
    RMGE_7 = "RMGE-7"
    LOCKWOOD_SMOOTHFIRE_12 = "LOCKWOOD SMOOTHFIRE 12"
    OVL_70_COMP = "OVL-70 COMP"
    VULTURE_CLAW_BREACHER = "VULTURE CLAW BREACHER"
    MACK8_FROST_BITE = "MACK8 FROST BITE"
    CROWN_BREAKER_CHOKE = "CROWN BREAKER CHOKE"
    XTEN_FULL_CHOKE = "XTEN FULL CHOKE"
    XTEN_MODIFIED_CHOKE = "XTEN MODIFIED CHOKE"
    BRYSON_IMPROVED_CHOKE = "BRYSON IMPROVED CHOKE"
    BRYSON_CHOKE = "BRYSON CHOKE"
    FLASH_TWIST_90 = "FLASH TWIST-90"
    XTEN_QUADFLASH = "XTEN QUADFLASH"
    FSS_THUNDERSTRIKE_BRAKE = "FSS THUNDERSTRIKE BRAKE"

    # added for LOCKWOOD 300 shotgun
    SAKIN_DB107 = "SAKIN DB107"
    TEMPUS_VOX = "TEMPUS VOX"
    GW_MAX_99 = "GW MAx-99"
    DB_BIG_BORE_COMP = "DB-BIG BORE COMP"
    DB_DREAD_COMP = "DB-DREAD COMP"
    MACK8_SHOTGUN_BREACH = "MACK8 SHOTGUN BREACH"
    XTEN_V1p3_CHOKE = "XTEN V1.3 CHOKE"
    BRYSON_SERIES_XII_CHOKE = "BRYSON SERIES XII CHOKE"
    RECKONER_COMP = "RECKONER COMP"
    XTEN_V2p0_CHOKE = "XTEN V2.0 CHOKE"
    BRYSON_SERIES_IX_CHOKE = "BRYSON SERIES IX CHOKE"

    # added for EXPEDITE 12 Shotgun
    LONG_HAUL_50 = "LONG HAUL 50"
    WOLFCALL_300 = "WOLFCALL 300"

    # added for XRK STALKER Sniper Rifle
    SA_SHROUD_FLASH_HIDER = "SA SHROUD FLASH HIDER"
    DEMON_HELIX_XL = "DEMON HELIX XL"
    VT7_SPIRITFIRE_SUPPRESSOR_XL = "VT-7 SPIRITFIRE SUPPRESSOR XL"
    XRK_NIGHTFALL_SUPPRESSOR_XL = "XRK NIGHTFALL SUPPRESSOR XL"
    MONOLITHIC_SUPPRESSOR_XL = "MONOLITHIC SUPPRESSOR XL"
    SONIC_SUPPRESSOR_XL = "SONIC SUPPRESSOR XL"
    COLOSSUS_SUPPRESSOR_XL = "COLOSSUS SUPPRESSOR XL"
    BRUEN_L40_KOBRA = "BRUEN L40 KOBRA"
    TALON_SIXTEEN_SILENCER = "TALON SIXTEEN SILENCER"
    NILSOUND_90_SILENCER = "NILSOUND 90 SILENCER"
    BRUEN_COUNTER_OPS = "BRUEN COUNTER OPS"
    STER45_SKYFURY_COMPENSATOR_XL = "STER45 SKYFURY COMPENSATOR XL"
    ELR_BLACKFIRE_COMPENSATOR_XL = "ELR BLACKFIRE COMPENSATOR XL"
    CASUS_BRAKE_XL = "CASUS BRAKE XL"
    MV50_MUZZLE_BRAKE = "MV50 MUZZLE BRAKE"
    H26_PORTED_COMP = "H26 PORTED COMP"
    VIGILANTE_COMP = "VIGILANTE COMP"
    LEGION_FIRE_COMP = "LEGION FIRE COMP"
    MAMMOTH_50_SUPPRESSOR = "MAMMOTH 50 SUPPRESSOR"

    # added for COR-45 Handgun
    HMRES_MOD_SUPPRESSOR_XS = "HMRES MOD SUPPRESSOR XS"
    MONOLITHIC_SUPPRESSOR_XS = "MONOLITHIC SUPPRESSOR XS"
    SONIC_SUPPRESSOR_XS = "SONIC SUPPRESSOR XS"
    COLOSSUS_SUPPRESSOR_XS = "COLOSSUS SUPPRESSOR XS"
    CN30_SUPPRESSOR = "CN30 SUPPRESSOR"
    FT_STEEL_FIRE = "FT STEEL FIRE"
    FORGE_DX30_S = "FORGE DX30-S"
    DZS_OPEN_COMP = "DZS OPEN COMP"
    SLAB_10_COMP = "SLAB-10 COMP"
    XRK_VENTOR_900 = "XRK VENTOR-900"
    COMP_905F_PISTOL = "COMP 905F PISTOL"
    BRUEN_TRI_PORT = "BRUEN TRI-PORT"
    CORVUS_SERIES_D = "CORVUS SERIES-D"
    HOLE_PUNCHER_BREACHER = "HOLE PUNCHER BREACHER"
    XRK_QZ_105 = "XRK QZ-105"
    SA_GF90_FLASH_HIDER = "SA GF90 FLASH HIDER"
    STER45_SKYFURY_COMPENSATOR_XS = "STER45 SKYFURY COMPENSATOR XS"
    ELR_BLACKFIRE_COMPENSATOR_XS = "ELR BLACKFIRE COMPENSATOR XS"
    VP27_MINI_BRAKE_XS = "VP27 MINI BRAKE XS"
    
    # added for GS .50 Handgun
    EXF_FIFTY_GS = "EXF FIFTY FS"
    MATUZEK_CROWN = "MATUZEK CROWN"
    FTAC_FIFTY_COMP = "FTAC FIFTY COMP"
    POTATO_MASHER = "POTATO MASHER"
    SA_PEAK_77 = "SA PEAK-77"
    GW_FLASH_FIFTY = "GW FLASH FIFTY"

    # added for BASILISK Handgun
    RVS607_COMPENSATOR = "RVS607 COMPENSATOR"
    FSS_KL30 = "FSS KL30"
    FTAC_H50_PORTED = "FTAC H50 PORTED"
    FSS_VMW_FLASH_HIDER = "FSS VMW FLASH HIDER"

    # added for FTAC SIEGE Handgun
    FTAC_SIEGE_CONTROL = "FTAC SIEGE CONTROL"

class Barrels(Enum):
    # added for SVA 545 Assault Rifle
    NO_MODIFICATIONS = "NO MODIFICATIONS"
    STV_PRECISION_BARREL = "STV PRECISION BARREL"
    WARPIG_SHORT_BARREL = "WARPIG SHORT BARREL"
    SA_LIGHTWEIGHT_CQC_BARREL = "SA LIGHTWEIGHT CQC BARREL"
    SVA_5_SHORT_BARREL = "SVA-5 SHORT BARREL"
    NT_QUIETUS_SUPPRESSED_BARREL = "NT QUIETUS SUPPRESSED BARREL"

    # added for RAM7 Assault Rifle
    FSS_IMPERATOR_LIGHT_BARREL = "FSS IMPERATOR LIGHT BARREL"
    XRK_COREMARK_40_HEAVY_BARREL = "XRK COREMARK 40 HEAVY BARREL"
    SPEEDWAY_V5_SHORT_BARREL = "SPEEDWAY V5 SHORT BARREL"
    CRONEN_HEADWIND_LONG_BARREL = "CRONEN HEADWIND LONG BARREL"
    BOREAL_6C_SUPPRESSED_BARREL = "BOREAL-6C SUPPRESSED BARREL"
    XTEN_FRL_3_HEAVY_BARREL = "XTEN FRL-3 HEAVY BARREL"
    FSS_FULLSTOP_BARREL = "FSS FULLSTOP BARREL"
    SO_KLONDIKE_45_LONG_BARREL = "SO KLONDIKE-45 LONG BARREL"

    # added for MTZ Assault Rifle
    MTZ_CLINCH_PRO_BARREL = "MTZ CLINCH PRO BARREL"
    MTZ_VLDL_3568_BARREL = "MTZ VLDL-3568 BARREL"
    MTZ_ROWAN_XL_356 = "MTZ ROWAN XL-356"
    MTZ_DRIFTER_HEAVY_LONG_BARREL = "MTZ DRIFTER HEAVY LONG BARREL"
    MTZ_PARA_LONG_BARREL = "MTZ PARA LONG BARREL"
    MTZ_NATTER_HEAVY_SHORT_BARREL = "MTZ NATTER HEAVY SHORT BARREL"

    # added for HOlGER Assault Rifle
    CROSS_X_SHORT_BARREL = "CROSS-X SHORT BARREL"
    BANNER_80_LIGHT_BARREL = "BANNER-80 LIGHT BARREL"
    CHRIOS_6_MATCH = "CHRIOS-6 MATCH"
    LM_INFLIX_SHORT_HEAVY_BARREL = "LM INFLIX SHORT HEAVY BARREL"

    # added for MCW Assault Rifle
    MCW_16p5_CYCLONE_LONG_BARREL = '16.5" MCW CYCLONE LONG BARREL'
    SL_CRATER_HEAVY_BARREL = "SL CRATER HEAVY BARREL"
    KIMURA_BLACKIRON_HEAVY_SHORT_BARREL = "KIMURA BLACKIRON HEAVY SHORT BARREL"
    SECOND_LINE_MAMMOTH_HEAVY_BARREL = "SECOND LINE MAMMOTH HEAVY BARREL"
    ORCHESTRA_40_SHORT_HEAVY_BARREL = "ORCHESTRA-40 SHORT HEAVY BARREL"
    KR_MIDNIGHT_13_BARREL = 'KR MIDNIGHT 13" BARREL'
    KIMURA_SILENTSHOT_INTEGRAL_SUPPRESSOR = "KIMURA SILENTSHOT INTREGRAL SUPPRESSOR"

    # added for DG-56 Assault Rifle
    DG_56_LS18_BARREL = "DG-56 LS18 BARREL"
    CDG_T_25_LIGHT_BARREL = "CDG T-25 LIGHT BARREL"
    AIGUO_DEFENDER_SHORT_BARREL = "AIGUO DEFENDER SHORT BARREL"
    CULPA_OGS_LIGHT_BARREL = "CULPA OGS LIGHT BARREL"
    DG_58_MICRO_BARREL = "DG-58 MICRO BARREL"

    # added for FR 5.56 Assault Rifle
    FR435_435MM = "435MM FR435"
    FR_LONGBORE_600MM = "600MM FR LONGBORE"
    FR_MINIBORE_395MM = "395MM FR MINIBORE"

    # added for TAQ56 Assault Rifle
    TACSHORT_12_BARREL = '12" TACSHORT BARREL'
    TUNDRA_PRO_17p5_BARREL = '17.5" TUNDRA PRO BARREL'

    # added for M4 Assault Rifle
    HIGHTOWER_20_BARREL = 'HIGHTOWER 20" BARREL'
    EXF_419MM_BARREL = "419MM EXF BARREL"
    CARBINE_SHROUD_14 = '14" CARBINE SHROUD'
    T_H4_11p5_BARREL = '11.5" T-H4 BARREL'
    CARBINE_SHROUD_11p5 = '11.5" CARBINE SHROUD'
    TEMPUS_TRENCH_PRO = "TEMPUS TRENCH PRO"
    TEMPUS_FIREBRAND_7p5 = '7.5" TEMPUS FIREBRAND'

    # added for STB556 Assault Rifle
    BRUEN_TURACO_686MM = "BRUEN TURACO 686MM"
    FTAC_FB20 = "FTAC FB20"
    BRUEN_GUERILLA_18 = '18" BRUEN GUERILLA'
    BRUEN_S620_20 = '20" BRUEN S-620'
    REAR_GUARD_508MM = "508MM REAR GUARD"
    BRUEN_S901_16p5_BARREL = '16.5" BRUEN S901 BARREL'

    # added for KASTOV 762 Assault Rifle
    KAS_10_584MM_BARREL = "KAS-10 584MM BARREL"
    KAS_7_406MM = "KAS-7 406MM"
    IG_K30_406MM = "IG-K30 406MM"
    KASTOVIA_343 = "KASTOVIA 343"
    SAKIN_KL_342MM = "342MM SAKIN KL"

    # added for M13B Assault Rifle
    BRUEN_ECHELON_14 = '14" BRUEN ECHELON'
    BRUEN_B_M20_7 = '7" BRUEN B-M20'
    M13C_FACTORY_BARREL = "M13C FACTORY BARREL"

    # added for CHIMERA Assault Rifle
    SA_PHOENIX_10 = '10" SA PHOENIX'
    EXF_OP_40_5p5 = '5.5" EXF OP-40'
    EXF_VORPAL_6p5 = '6.5" EXF VORPAL'

    # added for ISO HEMLOCK Assault Rifle
    RCQ_7 = "RCQ-7"
    SERIES_4_MR = "SERIES 4-MR"
    CIPHER_121 = "CIPHER-121"
    LR_30_56 = "LR-30/56"
    FIELDER_T50 = "FIELDER-T50"

    # added for TEMPUS RAZOR BACK
    TACK_2L_18 = '18" TACK-2L'
    FRENZY_IX_13 = '13" FRENZY IX'
    TANKR_V_16 = '16" TANKR-V'
    IO_XL_17 = '17" IO-XL'

    # added for M13C Assault Rifle
    BRUEN_FCT_6_10 = '10" BRUEN FCT-6'
    BRUEN_C_M20_7 = '7" BRUEN C-M20'

    # added for T76 GEIST Assault Rifle
    BRUEN_BRIDLE_60 = "BRUEN BRIDLE 60"
    LOCp5_LONG_BARREL = "LOC.5 LONG BARREL"
    LOCp2_SHORT_BARREL = "LOC.2 LONG BARREL"
    BRUEN_BRIDLE_HEAVY = "BRUEN BRIDLE HEAVY"
    FREIGHT_40_BARREL = "FREIGHT-40 BARREL"

    # added for LACHMANN 556 Assault Rifle
    LACHMANN_RAPP_15p9_BARREL = '15.9" LACHMANN RAPP BARREL'
    LACHMANN_NOVA = "LACHMANN NOVA"
    LM_AURORA_90_BARREL = "LM AURORA 90 BARREL"
    LACHSTRIKE_10p6_BARREL = '10.6" LACHSTRIKE BARREL'
    LACH_12_BARREL = "LACH-12 BARREL"

    # added for M16 Assault Rifle
    DEMO_501_FACTORY = "DEMO 501 FACTORY"

    # added for KASTOV74U Assault Rifle
    SA_ULTRA_III = "SA ULTRA III"
    SHORTTAC_190MM = "SHORTTAC 190MM"
    BR209_BARREL = "BR209 BARREL"
    KSTV_17 = "KSTV-17"

    # added for KASTOV545 Assault Rifle
    KASTOVIA_406 = "KASTOVIA 406"

    # added for BAS-B Battle Rifle
    BRUEN_VENOM_LONG_BARREL = "BRUEN VENOM LONG BARREL"
    SHORT_8_BRUEN_SZ_45_BARREL = 'SHORT 8" BRUEN SZ-45 BARREL'
    WYVERNS_RESPITE_LONG_BARREL = "WYVERN'S RESPITE LONG BARREL"
    CRIPPLING_MALICE_LIGHT_BARREL = "CRIPPLING MALICE LIGHT BARREL"
    LIGHT_9_BRUEN_WYVERN_SHORT_BARREL = 'LIGHT 9" BRUEN WYVERN SHORT BARREL'

    # added for SIDEWINDER Battle Rifle
    RATTLEBACK_DEADEYE_16_BARREL = 'RATTLEBACK DEADEYE 16" BARREL'
    TEMPUS_PREDATOR_PRECISION_BARREL = "TEMPUS PREDATOR PRECISION BARREL"
    RATTLEBACK_PRO_14p5_MAW_BARREL = 'RATTLEBACK PRO 14.5" MAW BARREL'
    HEAVY_BARREL_76L_P = "76L-P HEAVY BARREL"
    HUNTSMAN_SERIES_R_INTEGRATED_SUPPRESSOR_BARREL = "HUNTSMAN SERIES-R INTEGRATED SUPPRESSOR BARREL"

    # added for MTZ Battle Rifle
    MTZ_PRECISION_BLACKTHORN_BARREL = "MTZ-PRECISION BLACKTHORN BARREL"

    # added for LACHMANN Battle Rifle
    ROMEO_FT_16_BARREL = 'ROMEO FT 16" BARREL'
    MEER_56_11_FACTORY_BARREL = 'MEER-56 11" FACTORY BARREL'

    # added for CRONEN SQUALl Battle Rifle
    SB6p8_16 = 'SB6.8 16"'
    LR6p8_22 = 'LR6.8 22"'
    HR6p8_BARREL = "HR6.8 BARREL"

    # added for FTAC RECON Battle Rifle
    BULL_RIDER_16p5 = 'BULL RIDER 16.5"'

    # added for TAQ Battle Rifle
    LANCE_50_12_BARREL = 'LANCER-50 12" BARREL'
    PRECISION_6_18_BARREL = '18" PRECISION-6 BARREL'

    # added for SO-14 Battle Rifle
    FACTORY_FOURTEEN_22_BARREL = '22" FACTORY FOURTEEN BARREL'
    BOREMASTER_22_BARREL = '22" BOREMASTER BARREL'
    T300_18_BARREL = '18" T300 BARREL'
    CHROME_LINED_RFX40_16_BARREL = '16" CHROME-LINED RFX40 BARREL'

    # added for STRIKER SMG
    STRIKER_ELITE_LONG_BARREL = "STRIKER ELITE LONG BARREL"
    STRIKER_RECON_LONG_BARREL = "STRIKER RECON LONG BARREL"
    STRIKER_STUBBY_BARREL = "STRIKER STUBBY BARREL"

    # added for WSP SWARM SMG
    PESTILENCE_12_SHORT_COMPENSATED_BARREL = "PESTILENCE-12 SHORT COMPENSATED BARREL"
    WSP_OPTAC_LONG_BARREL = "WSP OPTAC LONG BARREL"
    WSP_RUTHLESS_L_BARREL = "WSP RUTHLESS-L BARREL"
    WSP_RECKLESS_90_LONG_BARREL = "WSP RECKLESS-90 LONG BARREL"
    WSP_ZIP_BARREL = "WSP ZIP BARREL"
    NOXIOUS_SHORT_COMPENSATED_BARREL = "NOXIOUS SHORT COMPENSATED BARREL"
    WSP_INFILTRATOR_INTEGRATED_SUPPRESSOR = "WSP INFILTRATOR INTEGRATED SUPPRESSOR"

    # added for AMR9 SMG
    AMR9_ENFORCER_LONG_BARREL = "AMR9 ENFORCER LONG BARREL"
    TECTONIC_MICRO_INTEGRAL_SUPPRESSOR = "TECTONIC MICRO INTEGRAL SUPPRESSOR"
    TECTONIC_HERALD_LIGHT_BARREL = "TECTONIC HERALD LIGHT BARREL"
    AMR9_COMMANDO_PRO_BARREL = "AMR9 COMMANDO PRO BARREL"
    NIMBUS_6_INTEGRATED_SUPPRESSOR = "NIMBUS-6 INTEGRATED SUPPRESSOR"

    # added for WSP-9 SMG
    HISS_SHORT_LIGHT_BARREL = "HISS SHORT LIGHT BARREL"

    # added for RIVAL-9 SMG
    RIVAL_C_CLEARSHOT_BARREL = "RIVAL-C CLEARSHOT BARREL"
    RIVAL_38E_FIRE_STARTER_BARREL = "RIVAL-38E FIRE STARTER BARREL"
    RIVAL_IGS_800_BARRE = "RIVAL IGS-800 BARRE"

    # added for LACHMANN SHROUD SMG
    GRAPPLE_VI_170MM = "170MM GRAPPLE VI"
    DARKSTAR_114MM = "114MM DARKSTAR"

    # added for ISO 9MM SMG
    ISO_45_FACTORY = "ISO 45 FACTORY"
    EX_RAPTOR_V2_7 = '7" EX RAPTOR-V2'
    PTX_TRAINER_9 = '9" PTX TRAINER'
    XLB_S_16 = '16" XLB-S'
    AXEBLADE_6 = '6" AXEBLADE'

    # added for PDSW SMG
    DUKE_30_9p5 = '9.5" DUKE-30'
    FTAC_SERIES_IX_14p5 = 'FTAC SERIES IX 14.5"'
    FTAC_DEFENSE_14p5 = 'FTAC DEFENSE 14.5"'
    CORVUS_PRORANGE_17 = '17" CORVUS PRORANGE'
    CLOAK_90_16 = '16" CLOAK-90'
    CLOAK_90_18p75 = '18.75" CLOAK-90'

    # added for VEL SMG
    TANGO_228_BARREL = "TANGO 228 BARREL"
    SCHLAGER_RV_B = "SCHLAGER RV-B"
    SCHLAGER_L203_BARREL = "SCHLAGER L203 BARREL"
    LACH_DX_203MM = "LACH-DX 203MM"
    LACHMANN_DART_165MM = "LACHMANN DART 165MM"
    LACH_152_ZULU = "LACH-152 ZULU"
    LM_SERIES_7 = "LM SERIES-7"

    # added for FENNEC SMG
    FENNEC_MINITAC_5p5 = '5.5" FENNEC MINITAC'
    FTAC_8p5_RECON = 'FTAC 8.5" RECON'
    FORGE_TAC_NINJA = "FORGE TAC NINJA"
    FENNEC_COVERT_FORCE = "FENNEC COVERT FORCE"
    ZLR_16p5_IGNITION_BARREL = 'ZLR 16.5" IGNITION BARREL'

    # added for BAS-P SMG
    BRUEN_SZ_36_12 = '12" BRUEN SZ-36'
    BRUEN_TYPHON_10p5 = '10.5" BRUEN TYPHON'
    BRUEN_DRAKE_6p5 = '6.5" BRUEN DRAKE'
    THUNDERFIRE_4 = '4" THUNDERFIRE'

    # added for ISO 45 SMG
    FRAME_S1_4 = '4" FRAME S-1'

    # added for LACHMANN SUB SMG
    FTAC_M_SUB_12 = 'FTAC M-SUB 12"'
    LACHMANN_PULSAR = "LACHMANN PULSAR"
    L38_FALCON_226MM = "L38 FALCON 226MM"

    # added for FSS HURRICANE SMG
    FSS_X7_BARREL = "FSS-X7_BARREL"
    FSS_CANNONADE_16 = 'FSS CANNONADE 16"'

    # added for MX9 SMG
    BRUEN_S901_16p5 = '16.5" BRUEN S901'
    STB_FACTORY_16p5 = '16.5" STB FACTORY'

    # added for MINIBAK SMG
    BAK_9_279MM_BARREL = 'BAK-9 279MM BARREL'

    # added for VAZNEV SMG
    KAS_1_254MM = "KAS-1 254MM"
    SA_RESPONSE_III = "SA RESPONSE III"

    # added for HRM 9 SMG
    THORN_90_BARREL = "THORN-90 BARREL"
    PRINCEPS_LONG_BARREL = "PRINCEPS LONG BARREL"
    TACITURN_7_SUPPRESSED_BARREL = "TACITURN-7 SUPPRESSED BARREL"

    # added for LOCKWOOD 680 shotgun
    BRYSON_HAMMERFORGED_LONG_BARREL = "BRYSON HAMMERFORGED LONG BARREL"
    LOCKWOOD_STALKER_HEAVY_SHORT_BARREL = "LOCKWOOD STALKER HEAVY SHORT BARREL"
    BRYSON_AGGRESSOR_712_SHORT_BARREL = "BRYSON AGGRESSOR 712 SHORT BARREL"
    LOCKWOOD_DEFENDER_HEAVY_LONG_BARREL = "LOCKWOOD DEFENDER HEAVY LONG BARREL"

    # added for HAYMAKER shotgun
    JAB_30_SHORT_BARREL = "JAB-30 SHORT BARREL"
    IMPERATOR_LONG_BARREL = "IMPERATOR LONG BARREL"

    # added for RIVETER shotgun
    SA_DRAVEN_20_LONG_BARREL = "SA DRAVEN-20 LONG BARREL"
    KILO_SHORT_BARREL = "KILO SHORT BARREL"
    JCX_L_SUPPRESSED_BARREL = "JCX_L_SUPPRESSED_BARREL"

    # added for LOCKWOOD 300 shotgun
    MATUZEK_812_BARREL = "MATUZEK 812 BARREL"
    MATUZEK_D50_711MM = "711MM MATUZEK D50"
    MATUZEK_INFERNO_597MM = "597MM MATUZEK INFERNO"
    BRYSON_SPECIAL_11 = '11" BRYSON SPECIAL'

    # added for EXPEDITE 12 shotgun
    EMPEROR_BARREL_18p5 = '18.5" EMPEROR BARREL'
    POLARIZE_BARREL_14 = '14" POLARIZE BARREL'
    SHORTY_BARREL_14 = '14" SHORTY BARREL'
    BATTLEMASTER_18p5 = '18.5" BATTLEMASTER'
    SCHLAGER_SALVO_419MM = "419MM SCHLAGER SALVO"

    # added for BRYSON 800 shotgun
    RIFLED_29p5_BARREL = '29.5" RIFLED BARREL'
    BRYSON_SHREDDER_21p5 = '21.5" BRYSON SHREDDER'
    RECOURSE_BARREL_21p5 = '21.5" RECOURSE BARREL'
    DEMO_FIREWALL_18 = '18" DEMO FIREWALL'
    BRYSON_FACTORY_16_BARREL = '16" BRYSON FACTORY BARREL'
    BRYSON_SHOCKWAVE_16 = '16" BRYSON SHOCKWAVE'
    XRK_CQB_8_BARREL = '8" XRK CQB BARREL'

    # added for KV BROADSIDE shotgun
    LTC_B = "LTC-B"
    WARRIOR_WOLF = "WARRIOR WOLF"
    RANGE_TWELVE = "RANGE TWELVE"
    DEADSIGHT_90 = "DEADSIGHT 90"
    VELOCIOUS_40 = "VELOCIOUS 40"
    GUNNER_D20 = "GUNNDER D20"
    ZLR_SPORT_XT = "ZLR SPORT XT"
    ZLR_SPORT_8 = "ZLR SPORT-8"

    # added for MX GUARDIAN shotgun
    MX_G_SHORT = "MX-G SHORT"
    MX_G_MOBILE = "MX-G MOBILE"
    HYP_LM = "HTP-LM"

    # added for BRYSON 890 shotgun
    RECOURSE_21p5 = '21.5" RECOURSE'
    BRYSON_TACFIRE_21p5 = '21.5" BRYSON TACFIRE'

    # added for TAQ EVOLVERE lmg
    HASTE_70_SHORT_BARREL = "HASTE-70 SHORT BARREL"
    LRF_RIGHTEOUS_LONG_BARREL = "LRF RIGHTEOUS LONG BARREL"
    EVICTION_762_HEAVY_BARREL = "EVICTION 762 HEAVY BARREL"

    # added for PULEMYOT lmg
    RECKONING_8_HEAVY_BARREL = "RECKONING-8 HEAVY BARREL"
    ST_PYRO_HEAVY_BARREL = "ST PYRO HEAVY BARREL"
    INVOKER_LIGHT_BARREL = "INVOKER LIGHT BARREL"
    SUPREMACTY_14_SHORT_BARREL = "SUPREMECY-14 SHORT BARREL"

    # added for DG56 lmg
    DG_EMPEROR_V_HEAVY_BARREL = "DG EMPEROR-V HEAVY BARREL"
    WUDI_LONG_BARREL = "WUDI LONG BARREL"
    DG_58_LS18_HEAVY_BARREL = "DG-58 LS18 HEAVY BARREL"

    # added for BRUEN MK9 lmg
    XRK_HORIZON_V2_23 = '23" XRK HORIZON V2'
    FT_FEROCITY_LR_BARREL = "FT FEROCITY LR BARREL"
    EXF_FORESIGHT_23_BARREL = '23" EXF FORESIGHT BARREL'
    BRUEN_18_PARA = 'BRUEN 18" PARA'

    # added for TAQ ERADICATOR lmg
    EXILER_84_SHORT_BARREL = "EXILER-84 SHORT BARREL"
    CONQUER_70_LONG_BARREL = "CONQUER-70 LONG BARREL"
    NULLIFIER_7_LIGHT_BARREL = "NULLIFIER-7 LIGHT BARREL"

    # added for HOLGER 26 lmg
    PRIME_LORD_HEAVY_BARREL = "PRIME LORD HEAVY BARREL"
    HOLGER_FACTORY_BARREL = "HOLGER FACTORY BARREL"
    HGL_92 = "HGL-92"

    # added for SAKIN lmg
    HGS_55_355MM = "355MM HGS-55"
    KYZYL_DAWN_BARREL = "KYZYL DAWN BARREL"
    BRUEN_SILVER_SERIES_20_BARREL = '20" BRUEN SILVER SERIES BARREL'

    # added for RAAL lmg
    EXF_GULF_16_BARREL = "EXF GULF-16 BARREL"
    EXF_RHINO_21_BARREL = '21" EXF RHINO BARREL'
    DEMO_FIELD_PRO_26p5_BARREL = '26.5" DEMO FIELD PRO BARREL'

    # added for ICARUS lmg
    FTAC_COLDFORGE_16_BARREL = 'FTAC COLDFORGE 16" BARREL'
    FTAC_SB = "FTAC SB"

    # added for RAPP H lmg
    MEER_76_449MM_FACTORY = "MEER-76 449MM FACTORY"
    
    # added for HCR lmg
    FTAC_HORNET_20_BARREL = 'FTAC HORNET 20" BARREL'

    # added for RPK lmg
    TAC_597_BARREL = "TAC 597 BARREL"
    KAS_7_406MM_BARREL = "KAS-7 406MM BARREL"

    # added for KVD ENFORCER marksman rifle
    KAS_10_584MM_MOD_BARREL = "KAS-10 584MM MOD BARREL"
    KASTOVIA_LPM_12 = "KASTOVIA LPM-12"
    KAS_DWORF_HEAVY_LONG_BARREL = "KAS-DWORF HEAVY LONG BARREL"
    KAS_7_INTEGRATED_SUPPRESSOR = "KAS-7 INTEGRATED SUPPRESSOR"
    KASTOVIA_JEK_40_BARREL = "KASTOVIA JEK-40 BARREL"

    # added for MCW 6.8 marksman rifle
    MCW_CROWN_30_BARREL = "MCW CROWN-30 BARREL"

    # added for DM56 marksman rifle
    ROR4_SEER = "ROR4 SEER"

    # added for MTZ INTERCEPTOR marksman rifle
    MTZ_LONGSHOT_PRO_BARREL = "MTZ LONGSHOT PRO BARREL"
    MTZ_BLACKTHORN_BARREL = "MTZ BLACKTHORN BARREL"

    # added for EBR marksman rifle
    LONESTAR_BARREL_18 = '18" LONESTAR BARREL'

    # added for SPR 208 marksman rifle
    ELEVATE_11_22p5 = '22.5" ELEVATE-11'
    FLUTED_R_67_23p5 = '23.5" FLUTED R-67'
    XRK_RESONATE_18p5 = '18.5" XRK RESONATE'
    ZLR_EXECUTOR_80_16_BARREL = '16" ZLR EXECUTOR 80 BARREL'
    CARBON_BARREL_12p5 = '12.5" CARBON BARREL'

    # added for LOCKWOOD MK2 marksman rifle
    LONESTAR_13p5_BARREL = '13.5" LONESTAR BARREL'
    LOCKWOOD_FRONTIERSMAN = "LOCKWOOD FRONTIERSMAN"
    COYOTE_21_BARREL = '21" COYOTE BARREL'
    BUFFALO_25_BARREL = '25" BUFFALO BARREL'
    EXF_ALAMO_22p5 = '22.5" EXF ALAMO'

    # added for TEMPUS TORRENT marksman rifle
    CHROMA_LRS = "CHROMA LRS"
    TOUR_RP_16 = '16" TOUR RP'
    OUTREACH_4_24 = '24" OUTREACH 4'
    RUGGED_ZN_12p5 = '12.5" RUGGED ZN'

    # added for SA-B 50 marksman rifle
    BRYSON_LR_FACTORY_18p5 = '18.5" BRYSON LR FACTORY'
    TAC_CB_55_9 = '9" TAC-CB 55'

    # added for TAQM marksman rifle
    THETA_X13_15p5 = '15.5" THETA-X13'
    LR1_7_20p5_BARREL = 'LR1:7 20.5" BARREL'

    # added for XRK STALKER sniper rifle
    HANDLER_LKP_SHORT_BARREL = "HANDLER LKP SHORT BARREL"
    KLX_09_SHORT_BARREL = "KLX-09 SHORT BARREL"
    XRK_STALKER_FACTORY_BARREL = "XRK STALKER FACTORY BARREL"
    FISSION_60_BARREL = "FISSION 60 BARREL"
    XRK_STOIC_4_SUPPRESSED_BARREL = "XRK STOIC-4 SUPPRESSED BARREL"

    # added for KATT sniper rifle
    TEMPUS_AURA_HEAVY_LONG_BARREL = "TEMPUS AURA HEAVY LONG BARREL"
    PERDITION_24_SHORT_BARREL = 'PERDITION 24" SHORT BARREL'
    ZANG_34_BARREL = "ZANG-34 BARREL"

    # added for LONGBOW sniper rifle
    TRU_TAC_SHORT_BARREL = "TRU-TAC SHORT BARREL"
    PRO_99_LONG_BARREL = "PRO-99 LONG BARREL"
    TAC_BRUTE_SUPPRESSED_BARREL = "TAC-BRUTE SUPPRESSED BARREL"

    # added for MCPR sniper rifle
    OMX_456_22 = '22" OMX-456'
    ORCA_BARREL_17p5 = '17.5" ORCA BARREL'
    SILENTFIRE_19_BARREL = '19" SILENTFIRE BARREL'

    # added for SIGNAL 50 sniper rifle
    TV_KILO_50_29 = '29" TV KILO-50'
    FSS_JETSTREAM = "FSS JETSTREAM"
    SA_FIFTY_H7_23p5 = '23.5" SA FIFTY-H7'
    FLUTED_FIFTY_21p5 = '21.5" FLUTED FIFTY'

    # added for VICTUS sniper rifle
    MACK_8_33p5_SUPER = "MACK 8 33.5 SUPER"
    MACK_8_21p5_SHORT = "MACK 8 21.5 SHORT"
    MAMMOTH_HB50_26 = '26" MAMMOTH HB50'
    EXECUTOR_546 = "EXECUTOR 546"

    # added for FJX sniper rifle
    FAHRENHEIT_29 = '29" FAHRENHEIT'
    LR_RETORT_29 = '29" LR-RETORT'
    TAC_COMMANDO_19 = 'TAC-COMMANDO 19"'
    CEROS_22 = 'CEROS 22"'
    CEROS_29 = 'CEROS 29"'

    # added for CARRACK sniper rifle
    CF_BIPOD_26_BARREL = '26" CF-BIPOD BARREL'
    FLINTLINE_30 = '30" FLINTLINE'
    FLINTFIRE_BIPOD_30 = '30" FLINTFIRE BIPOD'
    HEAVY_TAC_80 = "HEAVY-TAC 80"
    SUBSOUND_300 = "300 SUBSOUND"
    SUBSOUND_BIPOD_300 = "300 SUBSOUND BIPOD"

    # added for LA-B 330 sniper rifle
    CALVALRY_22_BARREL = '22" CALVALRY BARREL'

    # added for COR45 handgun
    XRK_SWIFTSHOT_LIGHT_BARREL = "XRK SWIFTSHOT LIGHT BARREL"
    XRK_PYRE_9_HEAVY_LONG_BARREL = "XRK PYRE-9 HEAVY LONG BARREL"

    # added for RENETTI handgun
    MLX_SHORT_COMPETITION_BARREL = "MLX SHORT COMPETITION BARREL"
    MK2_RENETTI_LONG_BARREL = "MK2 RENETTI LONG BARREL"
    MLX_EXTENDED_HEAVY_BARREL = "MLX EXTENDED HEAVY BARREL"

    # added for TYR handgun
    ZIU_16_HEAVY_LONG_BARREL = "ZIU-16 HEAVY LONG BARREL"
    HELS_REACH_SHORT_BARREL = "HEL'S REACH SHORT BARREL"
    LIMITLESS_V2_HEAVY_BARREL = "LIMITLESS V2 HEAVY BARREL"
    HUNTLOCK_LIGHT_BARREL = "HUNTLOCK LIGHT BARREL"

    # added for P890 handgun
    MATUZEK_COTTONMOUTH_BARREL = "MATUZEK COTTONMOUTH BARREL"
    XRK_TACOPS_BARREL = "XRK TACOPS BARREL"
    MATUZEK_VENOM = "MATUZEK VENOM"
    XTEN_HARBINGER = "XTEN HARBINGER"

    # added for GS 50 handgun
    SA_BRAKE_BARREL = "SA BRAKE BARREL"
    SA_COMP_BARREL = "SA COMP BARREL"
    SA_LONGSHOT_50 = "SA LONGSHOT-50"
    SA_TYRANT_FIFTY = "SA TYRANT FIFTY"

    # added for X12 handgun
    XRK_SIDEWINDER_6_SLIDE = "XRK SIDEWINDER-6 SLIDE"
    XRK_LUC_9 = "XRK LUC-9"

    # added for BASILISK handgun
    BRYSON_SNUBBY = "BRYSON SNUBBY"
    FTAC_FANG_PORTED = "FTAC FANG PORTED"
    CORVUS_COUGAR_500_6p75 = '6.75" CORVUS COUGAR 500'
    FTAC_ARROW_10p5 = '10.5" FTAC ARROW'
    FTAC_CARNIVORA_7 = 'FTAC CARNIVORA 7"'

    # added for FTAC SIEGE handgun
    RN5_XV_9MM = "RN5-XV 9MM"
    CMRN_50 = "CMRN-50"
    RATCHET_BE = "RATCHET BE"
    SUPERTAC_VI = "SUPERTAC-VI"
    RATCHET_BE_TAC = "RATCHET BE TAC"
    MOUSE_40 = "MOUSE 40"
    NST_81 = "NST-81"

    # added for 9MM DAEMON handgun
    EXF_OPAL_9 = "EXF OPAL-9"
    EXF_TROPE_H = "EXF TROPE-H"
    FT_COMPETITION = "FT COMPETITION"
    XTEN_WINDFALL = "XTEN WINDFALL"
    SA_LONGFIRE = "SA LONGFIRE"

    # added for X13 AUTO handgun
    IMPACT_POINT = "IMPACT POINT"

class Arms(Enum):
    NO_MODIFICATIONS = "NO MODIFICATIONS"
    CARBON_ELITE_V3 = "CARBON ELITE V3"
    QUILL_XE_100_LB = "QUILL XE 100 LB"
    SO_MOMENTI = "SO MOMENTI"
    THUNDER_200_LB = "THUNDER 200 LB"

class Lasers(Enum):
    # added for SVA 545 Assault Rifle
    NO_MODIFICATIONS = "NO MODIFICATIONS"
    SL_RAZORHAWK_LASER_LIGHT = "SL RAZORHAWK LASER LIGHT"
    CS15_SCARLET_BOX_LASER = "CS15 SCARLET BOX LASER"
    PRO_SAPPHIRE_BOX_LASER = "PRO SAPPHIRE BOX LASER"
    VERDANT_HOOK_BOX_LASER = "VERDANT HOOK BOX LASER"
    SZ_1MW_PEQ = "SZ 1MW PEQ"
    SCHLAGER_PEQ_BOX_IV = "SCHLAGER PEQ BOX IV"
    CORIO_LAZ_44_V3 = "CORIO LAZ-44 V3"
    FSS_OLE_V_LASER = "FSS OLE-V LASER"
    CANTED_VIBRO_DOT_7 = "CANTED_VIBRO_DOT_7"
    LASER_BOX_1MW = "1MW LASER BOX"
    STOVL_DR_LASER_BOX = "STOVL DR LASER BOX"
    CORVUS_PEQ_BEAM_5 = "CORVUS PEQ BEAM-5"
    FTAC_GRIMLINE_LASER = "FTAC GRIMLINE LASER"
    LUMINATE_44 = "LUMINATE-44"
    DXS_FLASH_90 = "DXS FLASH 90"

    # added for STB556 Assault Rifle
    CS15_SCARLET_CYLINDRICAL_LASER = "CS15 SCARLET CYLINDRICAL LASER"
    PRO_SAPPHIRE_CYLINDRICAL_LASER = "PRO SAPPHIRE CYLINDRICAL LASER"
    VERDANT_HOOK_CYLINDRICAL_LASER = "VERDANT HOOK CYLINDRICAL LASER"
    ARTEMIS_LASER_1MW = "1MW ARTEMIS LASER"
    QUICK_FIRE_LASER_1MW = "1MW QUICK FIRE LASER"
    ACCU_SHOT_5MW_LASER = "ACCU-SHOT 5MW LASER"
    VLK_LZR_7MW = "VLK LZR 7MW"
    CANTED_LASER_7MW = "7MW CANTED LASER"
    SCHLAGER_ULO_66_LASER = "SCHLAGER ULO-66 LASER"
    STOVL_TAC_LASER = "STOVL TAC LASER"
    HIPSHOT_L20 = "HIPSHOT L20"
    POINT_G3P_04 = "POINT-G3P 04"
    FJX_ULTRABEAM_XR = "FJX ULTRABEAM XR"
    EXF_SOLARFLARE = "EXF SOLARFLARE"
    KIMURA_RYL33_LASER_LIGHT = "KIMURA RYL33 LASER LIGHT"

    # added for COR45 Handgun
    KR_HX_15_LASER_LIGHT = "KR HX-15 LASER LIGHT"
    PRO_SAPPHIRE_MOUNTED_LASER = "PRO SAPPHIRE MOUNTED LASER"
    VERDANT_HOOK_MOUNTED_LASER = "VERDANT HOOK MOUNTED LASER"
    SERIES_710_PISTOL_LASER = "SERIES 710 PISTOL LASER"
    FJX_DIOD_70 = "FJX DIOD-70"
    XTEN_SIDEARM_L400 = "XTEN SIDEARM-L400"
    PISTOL_LASER_1MW = "1MW PISTOL LASER"
    DZM_1000_L = "DZM-1000 L"
    FTAC_VORTEX_200 = "FTAC VORTEX 200"
    CS15_SCARLET_MOUNTED_LASER = "CS15 SCARLET MOUNTED LASER"

    # added for BASILISK handgun
    BASILISK_GRIP_LASER = "BASILISK GRIP LASER"
    REVO_LSD_7MW = "REVO-LSD 7MW"
    CORVUS_LZR_790 = "CORVUS LZR-790"

class Optics(Enum):
    NO_MODIFICATIONS = "NO MODIFICATIONS"
    KR_INTLAS_LSJ_3 = "KR INTLAS LSJ-3"
    CRONEN_IRONS = "CRONEN IRONS"
    SLATE_REFLECTOR = "SLATE REFLECTOR"
    JAK_BULLSEYE = "JAK BULLSEYE" 
    SLIMLINE_PRO = "SLIMLINE PRO"
    SZ_MINI = "SZ MINI"
    CRONEN_MINI_DOT = "CRONEN MINI DOT"
    CRONEN_MINI_PRO = "CRONEN MINI PRO"
    SZ_SIGMA_IV_OPTIC = "SZ SIGMA-IV OPTIC"
    SZ_MINITAC_40 = "SZ_MINITAC-40"
    KR_MINITAC_40_RISER = "KR MINITAC-40 RISER"
    QTG_REFLEX_SIGHT = "QTG REFLEX SIGHT"
    CAUCASUS_REFLEX_SIGHT = "CAUCASUS REFLEX SIGHT"
    MK3_REFLECTOR = "MK. 3 REFLECTOR"
    DRAGONS_EYE_OPTIC = "DRAGONS' EYE OPTIC"
    RHINO_REFLEX = "RHINO REFLEX"
    XRK_ON_POINT_OPTIC = "XRK ON-POINT OPTIC"
    AIM_OP_V4 = "AIM OP-V4"
    DF105_REFLEX_SIGHT = "DF105 REFLEX SIGHT"
    MONOCLE_CT90 = "MONOCLE CT90"
    CORVUS_SOL_76 = "CORVUS SOL-76"
    SZ_RECHARGE_DX = "SZ RECHARGE-DX"
    SZ_SRO_7 = "SZ SRO-7"
    CORIO_RE_X_PRO = "CORIO RE-X PRO"
    CHRIOS_HOLO = "CHRIOS HOLO"
    CORIO_ENFORCER_OPTIC = "CORIO ENFORCER OPTIC"
    SZ_LONEWOLF_OPTIC = "SZ LONEWOLF OPTIC"
    KAZAN_HOLO = "KAZAN-HOLO"
    SZ_BATTLE_OPTIC = "SZ BATTLE OPTIC"
    CORVUS_DOWNRANGE_00 = "CORVUS DOWNRANGE-00"
    XTEN_ANGEL_40 = "XTEN ANGEL-40"
    SZ_HOLOTHERM = "SZ HOLOTHERM"
    CORIO_ELT_10_2p5 = "CORIO ELT-10 2.5"
    KR_MORTIS_PRECISION_2p5X = "KR MORTIS PRECISION 2.5X"
    SL_TRUESIGHT_2p5X = "SL TRUESIGHT 2.5X"
    KR_MARAUDER_9_RISER = "KR MARAUDER 9 RISER"
    TOS_NIGHTFALL_2p5X_THERMAL_OPTIC = "TOS NIGHTFALL 2.5X THERMAL OPTIC"
    AOK_4p0X_RQ_9_RECON = "AOK 4.0X RQ-9 RECON"
    TX4_HAVOC = "TX4 HAVOC"
    VLK_4p0_OPTIC = "VLK 4.0 OPTIC"
    SCHLAGER_3p4X = "SCHLAGER 3.4X"
    FORGE_TAC_DELTA_4 = "FORGE TAC DELTA 4"
    CRONEN_ZERO_P_OPTIC = "CRONEN ZERO-P OPTIC"
    SZ_BULLSEYE_OPTIC = "SZ BULLSEYE OPTIC"
    SZ_AGGRESSOR_IR_OPTIC = "SZ AGGRESSOR-IR OPTIC"
    SCHLAGER_NIGHT_VIEW = "SCHLAGER NIGHT VIEW"
    VX350_THERMAL_OPTIC = "VX350 THERMAL OPTIC"
    TEPLO_OP3_SCOPE = "TEPLO-OP3 SCOPE"
    HEINRICHTER_HYBRID_SCOPE = "HEINRICHTER HYBRID SCOPE"
    CORVUS_GHOSTVIEW = "CORVUS GHOSTVIEW"
    DR582_HYBRID_SIGHT = "DR582 HYBRID SIGHT"
    HYBRID_FIREPOINT = "HYBRID FIREPOINT"
    SZ_VOREX_90 = "SZ VOREX-90"
    BPZ40_HYBRID = "BPZ40 HYBRID"
    SZ_OSCAR_9 = "SZ OSCAR-9"
    ANGEL_40_4p8X = "ANGEL-40 4.8X"
    THERMO_OPTIC_X9 = "THERMO-OPTIC X9"
    TEPLO_CLEAR_SHOT = "TEPLO CLEAR SHOT"
    CORIO_CQC_SCOPE = "CORIO CQC SCOPE"
    DAUNT_C80 = "DAUNT-C80"
    FTAC_CHARLIE7 = "FTAC CHARLIE7"
    HMW_20_OPTIC = "HMW-20 OPTIC"
    LUCA_BANDERA_SCOPE = "LUCA BANDERA SCOPE"
    DS_FARSIGHT_11 = "DS FARSIGHT 11"
    RFL_OPTIC_3X = "3X RFL-OPTIC"
    DXS_CORIOLIS_V4 = "DXS CORIOLIS V4"
    LACHMANN_IMPACT_9 = "LACHMANN IMPACT 9"
    SPX_80_6p6X = "SP-X 80 6.6X"
    FTAC_LOCUS_SP = "FTAC LOCUS SP"
    LUCA_FIELD_6 = "LUCA FIELD-6"
    SZ_HEATSOURCE_800 = "SZ HEATSOURCE 800"
    HURRICANE_9_VARIABLE_OPTIC = "HURRICANE 9 VARIABLE OPTIC"
    SZ_ULTRA_11p5X = "SZ ULTRA 11.5X"
    MCPR_300_9p5X = "MCPR-300 9.5X"
    VICTUS_13X = "VICTUS 13X"
    IMPERIUM_12X = "IMPERIUM 12X"
    CARRACK_p300_11X = "CARRACK .300 11X"
    AKALINA_LR_STALK_OPTIC = "AKALINA LR-STALK OPTIC"
    KR_KATT_50_8X_SCOPE = "KR KATT-50 8X SCOPE"
    SHORT_ZOOM_6X_OPTIC = "6X SHORT-ZOOM OPTIC"
    SIGNAL_50_8X = "SIGNAL 50 8X"
    CORIO_13X_VRS = "CORIO 13X VRS"
    CORIO_SZ_HS_800 = "CORIO SZ-HS 800"
    RAPTOR_FVM40 = "RAPTOR-FVM40"
    DREXSOM_PRIME_90 = "DREXSOM PRIME-90"
    ARES_CLEAR_SHOT = "ARES CLEAR SHOT"
    SIGHTMAX_CLEAR_SHOT = "SIGHTMAX CLEAR SHOT"
    VIGILANT_30_C_IRON = "VIGILANT-30 C-IRON"
    LUCA_CANIS_4X_OPTIC = "LUCA CANIS 4X OPTIC"
    CORIO_RV500_OPTIC = "CORIO RV500 OPTIC"
    XTEN_ERX_10_MINI = "XTEN ERX-10 MINI"
    FSS_SPECTRE_MICROTHERM = "FSS SPECTRE MICROTHERM"
    NYDAR_MODEL_2023 = "NYDAR MODEL 2023"
    KR_V4_1X_RISER = "KR V4 1X RISER"
    TPS_INCENDIO_REFLEX = "TPS INCENDIO REFLEX"
    CORIO_EAGLESEYE_2p5X = "CORIO EAGLESEYE 2.5X",
    DEMONIC_CALL = "DEMOIC CALL"
    SZ_HM5_PRECISION_HYBRID_OPTIC = "SZ HM5 PRECISION HYBRID OPTIC"
    JOURNEYMAN_32_SCOPE = "JOURNEYMAN-32 SCOPE"
    CARRACK_6p3X_14X = "6.3X-14X CARRACK"
    HOLO_CRAFT_OPTIC = "HOLO-CRAFT OPTIC"
    HOUNDEYE_INTEGRATED_OPTIC = "HOUNDEYE INTEGRATED OPTIC"
    CRONEN_INTLAS_MSP_12 = "CRONEN INTLAS MSP-12"
    INTLAS_CAS_14 = "INTLAS CAS-14"
    JAK_GLASSLESS_OPTIC = "JAK GLASSLESS OPTIC"

class Stocks(Enum):
    # from https://game8.co/games/Modern-Warfare-3/archives/431917
    # used CHAT GPT to make most of enums (after MTZ assault rifle)
    A90_VENOM_STOCK = "A90 VENOM STOCK"
    AGILE_ASSAULT_7_STOCK = "AGILE ASSAULT-7 STOCK"
    ASCENT_LORD_STOCK = "ASCENT LORD STOCK"
    ASSAULT_60_STOCK = "ASSAULT-60 STOCK"
    ASSAULT_60_STOCK_FACTORY = "ASSAULT-60 STOCK FACTORY"
    B13_PAD = "B13 PAD"
    B66_PAD = "B66 PAD"
    BOMBARDIER_STOCK = "BOMBARDIER STOCK"
    BR_STOCKLESS_MOD = "BR STOCKLESS MOD"
    BROADSIDE_FCT = "BROADSIDE FCT"
    BRUEN_ARCHANGEL_MK2 = "BRUEN ARCHANGEL MK2"
    BRUEN_FLASH_V4_STOCK = "BRUEN FLASH V4 STOCK"
    BRUEN_FLASH_V8_LIGHT_STOCK = "BRUEN FLASH V8 LIGHT STOCK"
    BRUEN_HCR_56_STOCK = "BRUEN HCR 56 STOCK"
    BRUEN_LAUR4_LIGHT_PRECISION_STOCK = "BRUEN LAUR4 LIGHT PRECISION STOCK"
    BRUEN_MINUTEMAN_STOCK = "BRUEN MINUTEMAN STOCK"
    BRUEN_MX9_STOCK = "BRUEN MX9 STOCK"
    BRUEN_PUSH_STOCK = "BRUEN PUSH STOCK"
    BRUEN_R90_FACTORY = "BRUEN R90 FACTORY"
    BRUEN_STB_556_STOCK = "BRUEN STB 556 STOCK"
    BRUEN_THUNDER_V9_STOCK = "BRUEN THUNDER V9 STOCK"
    BRYSON_800_FACTORY_STOCK = "BRYSON 800 FACTORY STOCK"
    BRYSON_INFORCER_STOCK = "BRYSON INFORCER STOCK"
    BRYSON_NATURAL_SERIES_STOCK = "BRYSON NATURAL SERIES STOCK"
    BRYSON_REVERB_55_STOCK = "BRYSON REVERB-55 STOCK"
    BRYSON_STREAMLINE = "BRYSON STREAMLINE"
    CARRACK_OPS_STOCK = "CARRACK OPS STOCK"
    CHEETAH_STM_STOCK = "CHEETAH STM STOCK"
    COLLAPSED_STOCK = "COLLAPSED STOCK"
    CORIO_PRECIO_FACTORY = "CORIO PRECIO STOCK"
    CQB_STOCK = "CQB STOCK"
    CRONEN_LION_STOCK = "CRONEN LION STOCK"
    CRONEN_LW_88_STOCK = "CRONEN LW-88 STOCK"
    CRONEN_MARSHAL_STOCK = "CRONEN MARSHAL STOCK"
    CUT_OFF_STOCK_MOD = "CUT OFF STOCK MOD"
    DAV15_LIGHT_TACTICAL_STOCK = "DAV15 LIGHT TACTICAL STOCK"
    DEMO_D50_BUFFER_TUBE = "DEMO D50 BUFFER TUBE"
    DEMO_FADE_PRO_STOCK = "DEMO FADE PRO STOCK"
    DEMO_FADE_TAC = "DEMO FADE TAC"
    DEMO_FOLDING_STOCK = "DEMO FOLDING STOCK"
    DEMO_H_40 = "DEMO H-40"
    DEMO_LTS_STOCK = "DEMO LTS STOCK"
    DEMO_NIMBLE_STOCK = "DEMO NIMBLE STOCK"
    DEMO_PRECISION_ELITE_FACTORY = "DEMO PRECISION ELITE FACTORY"
    DEMO_QUICKSILVER_COLLAPSED = "DEMO QUICKSILVER COLLAPSED"
    DEMO_QUICKSILVER_STOCK = "DEMO QUICKSILVER STOCK"
    DEMO_RXT_STOCK = "DEMO RXT STOCK"
    DEMO_TAC_PAD = "DEMO TAC PAD"
    DEMO_VX509_STOCK = "DEMO VX509 STOCK"
    DEMO_XK12_LIGHT_TAC_STOCK = "DEMO XK12 LIGHT TAC STOCK"
    DUSTER_HEAVY_STOCK = "DUSTER HEAVY STOCK"
    EXF_CLOSE_QUARTERS_ASSAULT_STOCK = "EXF CLOSE QUARTERS ASSAULT STOCK"
    EXF_COLONEL = "EXF COLONEL"
    EXF_IMPACT_PAD = "EXF IMPACT PAD"
    EXO_TAC = "EXO-TAC"
    EXPEDITE_GRID_PAD = "EXPEDITE GRID PAD"
    EXTENDED_TP_9_BUTTPLATE = "EXTENDED TP-9 BUTTPLATE"
    FENNEC_BULLFIGHTER = "FENNEC BULLFIGHTER"
    FJX_KILO_TAC = "FJX KILO-TAC"
    FJX_LUX_7 = "FJX LUX-7"
    FJX_Z_PAD_9 = "FJX Z-PAD 9"
    FOLDING_STOCK = "FOLDING STOCK"
    FR_SPRINTER = "FR SPRINTER"
    FSS_CQC_STOCK = "FSS CQC STOCK"
    FSS_ECHO_STOCK = "FSS ECHO STOCK"
    FSS_FORTRESS_HEAVY_STOCK = "FSS FORTRESS HEAVY STOCK"
    FSS_FRAME_STOCK = "FSS FRAME STOCK"
    FSS_GUARDIAN_STOCK = "FSS GUARDIAN STOCK"
    FSS_HEAVY_STOCK_PRO = "FSS HEAVY STOCK PRO"
    FSS_MERC_STOCK = "FSS MERC STOCK"
    FSS_PRIORITY_TACTICAL_STOCK = "FSS PRIORITY TACTICAL STOCK"
    FSS_QUICKSLIDE_STOCK = "FSS QUICKSLIDE STOCK"
    FSS_RAMPAGE_VII_TACTICAL = "FSS RAMPAGE-VII TACTICAL"
    FSS_RAVAGER_45_STOCK = "FSS RAVAGER-45 STOCK"
    FSS_RIOT_STOCK = "FSS RIOT STOCK"
    FSS_WATCHMAN = "FSS WATCHMAN"
    FT_APEX_1_5 = "FT APEX 1.5"
    FT_DART_CB = "FT DART CB"
    FT_IRONBAR_STOCK = "FT IRONBAR STOCK"
    FT_MOBILE_STOCK = "FT MOBILE STOCK"
    FT_TAC_ELITE_STOCK = "FT TAC-ELITE STOCK"
    FT_TAC_ELITE_V3_STOCK = "FT TAC-ELITE V3 STOCK"
    FTAC_APOLLO_STOCK = "FTAC APOLLO STOCK"
    FTAC_CONDOR_STOCK = "FTAC CONDOR STOCK"
    FTAC_EZX_PRO = "FTAC EZX-PRO"
    FTAC_FOLDER = "FTAC FOLDER"
    FTAC_GOLIATH_XM250_HEAVY_STOCK = "FTAC GOLIATH XM250 HEAVY STOCK"
    FTAC_HEAVY_HUNTER_STOCK = "FTAC HEAVY HUNTER STOCK"
    FTAC_HOMELAND = "FTAC HOMELAND"
    FTAC_INVISI_670_STOCK = "FTAC INVISI-670 STOCK"
    FTAC_LOCKTIGHT_STOCK = "FTAC LOCKTIGHT STOCK"
    FTAC_PIERCER = "FTAC PIERCER"
    FTAC_RTP_40_STOCK = "FTAC RTP-40 STOCK"
    FTAC_SATUS_FOLDING_STOCK = "FTAC SATUS FOLDING STOCK"
    FTAC_SIEGE_STOCK = "FTAC SIEGE STOCK"
    FTAC_STOCK_CAP = "FTAC STOCK CAP"
    FTAC_VALOR_STOCK = "FTAC VALOR STOCK"
    FTAC_XCOMMAND_STOCK = "FTAC XCOMMAND STOCK"
    GUARD_DUTY_STOCK = "GUARD DUTY STOCK"
    HARDENED_RUBBER_CQC_BUTTPLATE = "HARDENED RUBBER CQC BUTTPLATE"
    HATCHET_LIGHT_STOCK = "HATCHET LIGHT STOCK"
    HEAVY_RECOIL_REDUCTION_STOCK_PAD = "HEAVY RECOIL REDUCTION STOCK PAD"
    HEAVY_SUPPORT_STOCK = "HEAVY SUPPORT STOCK"
    HEIST_STOCK_MOD = "HEIST STOCK MOD"
    HEIST_LW = "HEIST-LW"
    HELIX_LV_LIGHT_STOCK = "HELIX LV LIGHT STOCK"
    HELLHOUND_CARBINE_STOCK = "HELLHOUND CARBINE STOCK"
    HOLGER_26_FACTORY_STOCK = "HOLGER 26 FACTORY STOCK"
    HOLGER_556_FACTORY_STOCK = "HOLGER 556 FACTORY STOCK"
    HOLGER_RECOIL_PAD = "HOLGER RECOIL PAD"
    HOLGER_STOCKLESS_MOD = "HOLGER STOCKLESS MOD"
    HOLLOW_EXTENDED_STOCK = "HOLLOW EXTENDED STOCK"
    HUNKER_5_STOCK_PAD = "HUNKER-5 STOCK PAD"
    HVS_3p4_PAD = "HVS 3.4 PAD"
    IGNIS_F43_STOCK = "IGNIS F43 STOCK"
    INTERCEPTOR_FACTORY_STOCK = "INTERCEPTOR FACTORY STOCK"
    IRONHIDE_BRACE_STOCK = "IRONHIDE BRACE STOCK"
    ISO_STOCKLESS_MOD = "ISO STOCKLESS MOD"
    IVANOV_BLUFF_HEAVY_STOCK = "IVANOV BLUFF HEAVY STOCK"
    IVANOV_HSS_ERGONOMIC_STOCK = "IVANOV HSS ERGONOMIC STOCK"
    IVANOV_SUPPORT_BRACE = "IVANOV SUPPORT BRACE"
    IVANOV_WOOD_STOCK = "IVANOV WOOD STOCK"
    K_BLOC_STOCK = "K-BLOC STOCK"
    KASTOV_RAMA = "KASTOV-RAMA"
    KSTV_RPK_FACTORY = "KSTV RPK FACTORY"
    KV_FACTORY_STOCK = "KV FACTORY STOCK"
    KV_HEAVY_PADDED_STOCK = "KV HEAVY PADDED STOCK"
    LACHMANN_BR400_HEAVY_BRACE_STOCK = "LACHMANN BR400 HEAVY BRACE STOCK"
    LACHMANN_HAVOC_STOCK = "LACHMANN HAVOC STOCK"
    LACHMANN_MK2_LIGHT_STOCK = "LACHMANN MK2 LIGHT STOCK"
    LACHMANN_NEMESIS_10_STOCK = "LACHMANN NEMESIS-10 STOCK"
    LACHMANN_RECON_SERIES_STOCK = "LACHMANN RECON SERIES STOCK"
    LACHMANN_S76_FACTORY_STOCK = "LACHMANN S76 FACTORY STOCK"
    LACHMANN_S9_FACTORY = "LACHMANN S9 FACTORY"
    LANE_56_STOCK = "LANE-56 STOCK"
    LEX_V14_STOCK = "LEX V14 STOCK"
    LIGHTWEIGHT_RUBBERIZED_STOCK_PAD = "LIGHTWEIGHT RUBBERIZED STOCK PAD"
    LM_PRECISION_STOCK = "LM PRECISION STOCK"
    LM_S_FACTORY_G79_STOCK = "LM-S FACTORY G79 STOCK"
    LM_STOCKLESS_MOD = "LM STOCKLESS MOD"
    LOCKWOOD_BULLSEYE_STOCK = "LOCKWOOD BULLSEYE STOCK"
    M13C_FACTORY_STOCK = "M13C FACTORY STOCK"
    M13C_FS_COLLAPSED = "M13C FS COLLAPSED"
    MACE_600 = "MACE 600"
    MACE_650 = "MACE 650"
    MARKEEV_R7_STOCK = "MARKEEV R7 STOCK"
    MAKEEV_R11_STOCK = "MAKEEV R11 STOCK"
    MANE_V6_STOCK = "MANE V6 STOCK"
    MAX_DMR_PRECISION = "MAX DMR PRECISION"
    MCW_BLACKJACK = "MCW BLACKJACK"
    MCW_IRONBARK_TACTICAL_STOCK = "MCW IRONBARK TACTICAL STOCK"
    MEER_RECOIL_56_FACTORY_STOCK = "MEER RECOIL-56 FACTORY STOCK"
    MK_DCP_0 = "MK DCP-0"
    MK_VIPER_MARKSMAN_STOCK = "MK VIPER MARKSMAN STOCK"
    MODEL_1957_STOCK = "MODEL 1957 STOCK"
    MOTION_TAC_PAD = "MOTION-TAC PAD"
    MTZ_LITESTRIKE_TELESCOPIC_STOCK = "MTZ LITESTRIKE TELESCOPIC STOCK"
    MTZ_MARAUDER_STOCK = "MTZ MARAUDER STOCK"
    MTZ_STOCKLESS_MOD = "MTZ STOCKLESS MOD"
    MW8_RUTHLESS_HEAVY_STOCK = "MW8 RUTHLESS HEAVY STOCK"
    MX_DCP_0 = "MX DCP-0"
    NO_MODIFICATIONS = "NO MODIFICATIONS"
    NO_STOCK = "NO STOCK"
    NO_STOCK_MOD = "NO STOCK MOD"
    OPR_THREAT = "OPR THREAT"
    OORT_6_PRECISION_STOCK = "OORT-6 PRECISION STOCK"
    OTREZAT_STOCK = "OTREZAT STOCK"
    PIPELINE_PRO_LTS = "PIPELINE PRO LTS"
    PRECISION_STOCK_PAD = "PRECISION STOCK PAD"
    PROLITE_TL3_STOCK = "PROLITE TL3 STOCK"
    PSO_HEAVY = "PSO HEAVY"
    PVZ_890_TAC_STOCK = "PVZ-890 TAC STOCK"
    R_COM_S4 = "R-COM S4"
    RAID_90 = "RAID 90"
    RAPP_762_FACTORY = "RAPP-762 FACTORY"
    RAMPART_HEAVY_STOCK = "RAMPART HEAVY STOCK"
    RAVAGE_8 = "RAVAGE-8"
    RAVAGE_10 = "RAVAGE-10"
    RAVAGE_CS = "RAVAGE-CS"
    RAVAGE_L56 = "RAVAGE L56"
    RAVAGE_20_HEAVY_STOCK = "RAVAGE-20 HEAVY STOCK"
    RB_ADDLE_ASSAULT_STOCK = "RB ADDLE ASSAULT STOCK"
    RB_PRECISION_HEAVY_STOCK = "RB_PRECISION_HEAVY_STOCK"
    RB_REGAL_HEAVY_STOCK = "RB REGAL HEAVY STOCK"
    RB_CROTALUS_ASSAULT_STOCK = "RB CROTALUS ASSAULT STOCK"
    RECOIL_REDUCTION_BUTTPLATE = "RECOIL REDUCTION BUTTPLATE"
    RECON_STOCK_PAD = "RECON STOCK PAD"
    REGENCY_12_STOCK_PAD = "REGENCY-12 STOCK PAD"
    RELENTLESS_TACTICAL_STOCK = "RELENTLESS TACTICAL STOCK"
    RES_2 = "RES-2"
    RESONANCE_STOCK_COLLAPSED = "RESONANCE STOCK COLLAPSED"
    RIB400 = "RIB400"
    RIVAL_DMH_IV = "RIVAL DMH IV"
    RIVAL_FA_TACTICAL_STOCK = "RIVAL-FA TACTICAL STOCK"
    RUSTLER_PAD = "RUSTLER PAD"
    SA_KILONOVA_STOCK = "SA KILONOVA STOCK"
    SAKIN_RIPTIDE_STOCK = "SAKIN RIPTIDE STOCK"
    SAWED_OFF_MOD = "SAWED OFF MOD"
    SCHLAGER_RESONANCE = "SCHLAGER RESONANCE"
    SCOUT_LD_STOCK_PAD = "SCOUT-LD STOCK PAD"
    SERAPH_14_HEAVY_CARBINE_STOCK = "SERAPH-14 HEAVY CARBINE STOCK"
    SIEGE_WIRE_STOCK = "SIEGE WIRE STOCK"
    SK_3_CHEETAH = "SK-3 CHEETAH"
    SKELLY_FOLDING_STOCK = "SKELLY FOLDING STOCK"
    SL_WARFORGED_PRECISION_STOCK = "SL WARFORGED PRECISION STOCK"
    SL_COLLAPSED_STOCKLESS_MOD = "SL COLLAPSED STOCKLESS MOD"
    SMOOTH_FIRE_SNIPER_STOCK = "SMOOTH FIRE SNIPER STOCK"
    SO_90_FACTORY_STOCK = "SO-90 FACTORY STOCK"
    SO_INLINE_STOCK = "SO INLINE STOCK"
    SO_R55_ADAPTOR = "SO R55 ADAPTOR"
    SOLDIER_PRO_PADDED_BUTTPLATE = "SOLDIER PRO PADDED BUTTPLATE"
    SPEEDTRAK_ECHO = "SPEEDTRAK ECHO"
    SPETSNAZ_S10_STOCK = "SPETSNAZ S10 STOCK"
    STOCKLESS_PISTOL_GRIP = "STOCKLESS PISTOL GRIP"
    STOVL_CONQUEROR_V_STOCK = "STOVL CONQUEROR-V STOCK"
    STRIKER_FACTORY_STOCK = "STRIKER FACTORY STOCK"
    SVA_FACTORY_STOCK = "SVA FACTORY STOCK"
    SWEETSPOT_STOCK = "SWEETSPOT STOCK"
    TA_ERGO = "TA ERGO"
    TA_VENOM_STOCK = "TA VENOM STOCK"
    TAC_840C_STOCK = "TAC 840C STOCK"
    TACTICAL_STOCK_PAD = "TACTICAL STOCK PAD"
    TACTIQUE_BRUTE_STOCK = "TACTIQUE BRUTE STOCK"
    TACVERTE_CORE_STOCK = "TACVERTE CORE STOCK"
    TEMPUS_P80_STRIKE_STOCK = "TEMPUS P80 STRIKE STOCK"
    TORRENT_SPAN_9 = "TORRENT SPAN-9"
    TOUR_56_STOCK = "TOUR-56 STOCK"
    TR_PREAMBLE = "TR PREAMBLE"
    TRX_56_STOCK = "TRX-56 STOCK"
    TV_BALLAST_STOCK = "TV BALLAST STOCK"
    TV_CARDINAL_STOCK = "TV CARDINAL STOCK"
    TV_LPX_434 = "TV LPX-434"
    TV_XLINE_PRO = "TV XLINE PRO"
    ULS_RECOIL_STOCK_PAD = "ULS RECOIL STOCK PAD"
    ULTRA_LIGHT_STOCK_PAD = "ULTRA-LIGHT STOCK PAD"
    URAL_M_STOCK = "URAL-M STOCK"
    VEL_A_568_COLLAPSED = "VEL A-568 COLLAPSED"
    VLK_STOCKLESS = "VLK STOCKLESS"
    WMG_TAC = "WMG-TAC"
    WOLFHOUND_CARBINE_STOCK = "WOLFHOUND CARBINE STOCK"
    WSP_CLASSICS_FACTORY_STOCK = "WSP CLASSICS FACTORY STOCK"
    WSP_FACTORY_STOCK = "WSP FACTORY STOCK"
    WSP_RAMPART_IV_STOCK = "WSP RAMPART-IV STOCK"
    X13_COACHWHIP_STOCK = "X13 COACHWHIP STOCK"
    XF23_STILT_STOCK = "XF23 STILT STOCK"
    XRK_BAR_STOCK = "XRK BAR STOCK"
    XRK_BULLSEYE = "XRK BULLSEYE"
    XRK_DYNAMIC_PRECISION_STOCK = "XRK DYNAMIC PRECISION STOCK"
    XRK_PISTOL_STOCK = "XRK PISTOL STOCK"
    XRK_MONUMENT_HEAVY_STOCK = "XRK MONUMENT HEAVY STOCK"
    XRK_RISE_50 = "XRK RISE 50"
    XRK_SPECTER_MOD = "XRK SPECTER MOD"
    XRK_TACTICAL_STOCK = "XRK TACTICAL STOCK"
    XTEN_ASSAULT_90_STOCK = "XTEN ASSAULT-90 STOCK"
    XTEN_RIPCORD_STOCK = "XTEN RIPCORD STOCK"
    XTEN_TACTICAL_MATCH_STOCK = "XTEN TACTICAL MATCH STOCK"
    ZLR_BULWARK_PRECISION_STOCK = "ZLR BULWARK PRECISION STOCK"
    ZLR_STRELK_STOCK = "ZLR STRELK STOCK"
    ZLR_T70_PAD_EXTENSION = "ZLR T70 PAD EXTENSION"
    ZRL_T70_PAD_EXTENSION = "ZRL T70 PAD EXTENSION"

class Combs(Enum):
    # from https://game8.co/games/Modern-Warfare-3/archives/431917
    # used CHAT GPT to make enum
    AIM_ASSIST_406 = "AIM-ASSIST 406"
    BRUEN_TS_30_COMB = "BRUEN TS-30 COMB"
    CHISEL_VX_0_CHEEK_RISER = "CHISEL VX-0 CHEEK RISER"
    CRONEN_GI40_CHEEK_RISER = "CRONEN GI40 CHEEK RISER"
    DEMO_FLAK_COMB = "DEMO FLAK COMB"
    EXF_TRAPPER_COMB = "EXF TRAPPER COMB"
    FARSEER_CHEEK_RISER = "FARSEER CHEEK RISER"
    FR_ANCHOR = "FR ANCHOR"
    FR_GIGA = "FR GIGA"
    FR_TON_618 = "FR TON-618"
    FSS_AMMO_SLEEVE = "FSS AMMO SLEEVE"
    FSS_EL_T_POUCH = "FSS EL-T POUCH"
    FSS_HARDTOP_COMB = "FSS HARDTOP COMB"
    FSS_LAST_STAND_COMB = "FSS LAST STAND COMB"
    FSS_LS_3_COMB = "FSS LS-3 COMB"
    FT_POLYCOMB = "FT POLYCOMB"
    FTAC_C11_RISER = "FTAC C11 RISER"
    FTAC_H86_CHEEK_REST = "FTAC H86 CHEEK REST"
    H1_PRECISION = "H1 PRECISION"
    LACHMANN_X_TRA_POUCH = "LACHMANN X-TRA POUCH"
    LOCKWOOD_DEFENDER_COMB = "LOCKWOOD DEFENDER COMB"
    LOCKWOOD_MERCILESS = "LOCKWOOD MERCILESS"
    LTX_ECLIPSE = "LTX ECLIPSE"
    MACK_8_ONTRAK_COMB = "MACK 8 ONTRAK COMB"
    NO_MODIFICATIONS = "NO MODIFICATIONS"
    PADDED_SHELL_SLEEVE = "PADDED SHELL SLEEVE"
    PADDED_SHOTGUN_COMB = "PADDED SHOTGUN COMB"
    PD_A40_SLEEVE = "PD-A40 SLEEVE"
    RECON_COMB = "RECON COMB"
    SAB_COMB = "SAB COMB"
    SCHLAGER_HONOR_COMB = "SCHLAGER HONOR COMB"
    SCHLAGER_TTF3_RISER = "SCHLAGER TTF3 RISER"
    SL_K_TRIM = "SL-K TRIM"
    TAC_COMB_5GN = "5GN TAC-COMB"
    TV_TACCOMB = "TV TACCOMB"
    WARRANT_CONTROL_COMB = "WARRANT CONTROL COMB"
    WINGMAN_COMB = "WINGMAN COMB"

class Guards(Enum):
    # from https://game8.co/games/Modern-Warfare-3/archives/431917
    # used CHAT GPT to make enum
    AZ_40_SHOTGUARD = "AZ-40 SHOTGUARD"
    AZAROV_T15 = "AZAROV T15"
    BRYSON_NATURAL_SERIES_HANDGUARD = "BRYSON NATURAL SERIES HANDGUARD"
    BUCK_PRO = "BUCK-PRO"
    CORVUS_RESPONDER = "CORVUS RESPONDER"
    DEMO_CARBON_GUARD = "DEMO CARBON GUARD"
    DEMO_DROPZONE_PUMP = "DEMO DROPZONE PUMP"
    DEMO_X40_TACTICAL_PUMP = "DEMO X40 TACTICAL PUMP"
    DEMO_X50_TACTICAL_PUMP = "DEMO X50 TACTICAL PUMP"
    HVS_50_CAL_HEAVY_GUARD = "HVS 50 CAL HEAVY GUARD"
    LOCKWOOD_COMBAT_GUARD = "LOCKWOOD COMBAT GUARD"
    LOCKWOOD_COMMANDO_GUARD = "LOCKWOOD COMMANDO GUARD"
    LOCKWOOD_SADDLE_GUARD = "LOCKWOOD SADDLE GUARD"
    LOCKWOOD_SERIES_II = "LOCKWOOD SERIES II"
    LOCKWOOD_SIGNATURE_SERIES_HEAVY_GUARD = "LOCKWOOD SIGNATURE SERIES HEAVY GUARD"
    MATUZEK_LIGHTBEARER_ERGO_GUARD = "MATUZEK LIGHTBEARER ERGO GUARD"
    MATUZEK_XRAY_SKELETONIZED_GUARD = "MATUZEK XRAY SKELETONIZED GUARD"
    NO_MODIFICATIONS = "NO MODIFICATIONS"
    QUARTER_03_LIGHT_GUARD = "QUARTER-03 LIGHT GUARD"
    TORRENT_MOC_IV = "TORRENT MOC-IV"
    TORRENT_TAC_GUARD = "TORRENT TAC GUARD"
    TT_HG_40 = "TT-HG 40"
    TV_CF40_GUARD = "TV CF40 GUARD"

class Bolts(Enum):
    # from https://game8.co/games/Modern-Warfare-3/archives/431917
    # used CHAT GPT to make enum
    BLASTCAP_20_BOLTS = "BLASTCAP 20\" BOLTS"
    BRIGHTBLAZE_20_BOLTS = "BRIGHTBLAZE 20\" BOLTS"
    CRONEN_B85_BOLT = "CRONEN B85 BOLT"
    CRONEN_SMOOTH_BOLT = "CRONEN SMOOTH BOLT"
    DASHBOLT_60 = "DASHBOLT 60"
    EPHEMERAL_QUICKBOLT = "EPHEMERAL QUICKBOLT"
    EXPEDITE_HZ3_BOLT = "EXPEDITE HZ3 BOLT"
    EXPEDITE_L_BOLT = "EXPEDITE L-BOLT"
    EXPRESS_LIGHT_BOLT = "EXPRESS LIGHT BOLT"
    FJX_BLAST = "FJX BLAST"
    FJX_H_BOLT = "FJX H-BOLT"
    FSS_ST87_BOLT = "FSS ST87 BOLT"
    FTAC_CAUSTIC_20_BOLTS = "FTAC CAUSTIC 20\" BOLTS"
    HARDBOLT_2_1 = "HARDBOLT 2.1"
    NO_MODIFICATIONS = "NO MODIFICATIONS"
    REQUIEM_9_HEAVY_BOLT = "REQUIEM-9 HEAVY BOLT"
    SA_M_LONGDRAW = "SA-M LONGDRAW"
    SA_M_QUICKBOLT = "SA-M QUICKBOLT"
    STALKER_HEAVY_BOLT = "STALKER HEAVY BOLT"
    TITANIC_HEAVY_BOLT = "TITANIC HEAVY BOLT"
    XRK_STALKER_LIGHT_BOLT = "XRK STALKER LIGHT BOLT"
    ZLR_REINFORCED_LOCKBOLT = "ZLR REINFORCED LOCKBOLT"

class Levers(Enum):
    LONGHORN_LEVER = "LONGHORN LEVER"
    NO_MODIFICATIONS = "NO MODIFICATIONS"
    STALLION_LEVER = "STALLION LEVER"

class RearGrips(Enum):
    # from https://game8.co/games/Modern-Warfare-3/archives/431912
    # used CHAT GPT to generate list
    A30_STOUT = 'A30 STOUT'
    AKIMBO_50_GS = 'AKIMBO .50 GS'
    AKIMBO_9MM_DAEMON = 'AKIMBO 9MM DAEMON'
    AKIMBO_BASILISK = 'AKIMBO BASILISK'
    AKIMBO_COR_45 = 'AKIMBO COR-45'
    AKIMBO_FTAC_SIEGE = 'AKIMBO FTAC SIEGE'
    AKIMBO_P890 = 'AKIMBO P890'
    AKIMBO_RENETTI = 'AKIMBO RENETTI'
    AKIMBO_TYR = 'AKIMBO TYR'
    AKIMBO_WSP_STINGER = 'AKIMBO WSP STINGER'
    AKIMBO_X12 = 'AKIMBO X12'
    AKIMBO_X13 = 'AKIMBO X13'
    AVALANCHE_PALMREST_GRIP = 'AVALANCHE PALMREST GRIP'
    BLITZ_TACTICAL_GRIP = 'BLITZ TACTICAL GRIP'
    BP_GRAIN_GRIP = 'BP-GRAIN GRIP'
    BRACE_LS = 'BRACE LS'
    BROADSIDE_FACTORY_GRIP = 'BROADSIDE FACTORY GRIP'
    BRUEN_AGRO_76_GRIP = 'BRUEN AGRO-76 GRIP'
    BRUEN_ANCHOR_GRIP = 'BRUEN ANCHOR GRIP'
    BRUEN_B60 = 'BRUEN B60'
    BRUEN_FLASH_GRIP = 'BRUEN FLASH GRIP'
    BRUEN_G305_GRIP_WRAP = 'BRUEN G305 GRIP WRAP'
    BRUEN_GR_500 = 'BRUEN GR-500'
    BRUEN_LYNX_GRIP = 'BRUEN LYNX GRIP'
    BRUEN_ONSLAUGHT_ASSAULT_GRIP = 'BRUEN ONSLAUGHT ASSAULT GRIP'
    BRUEN_Q900_GRIP = 'BRUEN Q900 GRIP'
    BRUEN_Q900_GRIP_WRAP = 'BRUEN Q900 GRIP WRAP'
    BRUEN_RSH_80_GRIP = 'BRUEN RSH-80 GRIP'
    BRUEN_TR_24_ASSAULT_GRIP = 'BRUEN TR-24 ASSAULT GRIP'
    BRYSON_DUEL_GRIP = 'BRYSON DUEL GRIP'
    BRYSON_WD_85_GRIP = 'BRYSON WD-85 GRIP'
    CARRACK_PALM = 'CARRACK PALM'
    CASUS_X = 'CASUS X'
    CENTER_MASS_GRIP_TAPE = 'CENTER MASS GRIP TAPE'
    CHORUS_GEN4_GRIP = 'CHORUS GEN4 GRIP'
    CITADEL_GRIP = 'CITADEL GRIP'
    CP60_GRIP = 'CP60 GRIP'
    CRONEN_BLOCKADE_GRIP = 'CRONEN BLOCKADE GRIP'
    CRONEN_CHEETAH_GRIP = 'CRONEN CHEETAH GRIP'
    CRONEN_EM55_GRIP = 'CRONEN EM55 GRIP'
    CRONEN_ERGO = 'CRONEN ERGO'
    CRONEN_GRIP_WRAP = 'CRONEN GRIP WRAP'
    CRONEN_LIMA_6 = 'CRONEN LIMA-6'
    CRONEN_RESISTOR_GRIP = 'CRONEN RESISTOR GRIP'
    CRONEN_RFX_300 = 'CRONEN RFX-300'
    CRONEN_ZERO_GRIP = 'CRONEN ZERO GRIP'
    CT2000_TACTICAL_GRIP = 'CT2000 TACTICAL GRIP'
    D15_GRIP = 'D15 GRIP'
    D37_GRIP = 'D37 GRIP'
    DAEMON_HAND = 'DAEMON HAND'
    DANA_7_PALMREST = 'DANA-7 PALMREST'
    DEMO_650_GRIP = 'DEMO 650 GRIP'
    DEMO_ASSAULT_BREAKER_GRIP = 'DEMO ASSAULT BREAKER GRIP'
    DEMO_CLEANSHOT_GRIP = 'DEMO CLEANSHOT GRIP'
    DEMO_TL20_RECOIL_GRIP = 'DEMO TL20 RECOIL GRIP'
    DEMO_X2_GRIP = 'DEMO-X2 GRIP'
    EIRS_RESPITE = "EIR'S RESPITE"
    ENGAGE_20_GRIP = 'ENGAGE-20 GRIP'
    ERG_X1 = 'ERG-X1'
    EXF_ECLIPSOR_GRIP = 'EXF ECLIPSOR GRIP'
    EXF_RESISTANCE_GRIP = 'EXF RESISTANCE GRIP'
    EXF_SHORELINE_GRIP = 'EXF SHORELINE GRIP'
    EXP_SHEAR = 'EXP SHEAR'
    FENNEC_RUBBER_GRIP = 'FENNEC RUBBER GRIP'
    FENNEC_STIPPLED_GRIP = 'FENNEC STIPPLED GRIP'
    FENNEC_TEXTURED_GRIP = 'FENNEC TEXTURED GRIP'
    FJX_DVF60_GRIP = 'FJX DVF60 GRIP'
    FLT_22 = 'FLT-22'
    FR_TACK_3 = 'FR TACK-3'
    FRIGGS_EMBRACE = "FRIGG'S EMBRACE"
    FSS_COMBAT_GRIP = 'FSS COMBAT GRIP'
    FSS_EBONHAWK_TACTICAL_GRIP = 'FSS EBONHAWK TACTICAL GRIP'
    FSS_GEN_7_GRIP = 'FSS GEN.7 GRIP'
    FSS_GUARDIAN_ASSAULT_GRIP = 'FSS GUARDIAN ASSAULT GRIP'
    FSS_MATCH_ASSAULT_GRIP = 'FSS MATCH ASSAULT GRIP'
    FSS_SPIDER_GRIP = 'FSS SPIDER GRIP'
    FSS_STORMENDER_ASSAULT_GRIP = 'FSS STORMENDER ASSAULT GRIP'
    FT_MATCH_GRIP = 'FT MATCH GRIP'
    FTAC_G_5_EXO = 'FTAC G-5 EXO'
    FTAC_HOLD = 'FTAC HOLD'
    FTAC_OL_Z_GRIP = 'FTAC OL-Z GRIP'
    FTAC_STEAD = 'FTAC STEAD'
    GOLIATH_77_GRIP = 'GOLIATH 77 GRIP'
    GRANULAR_GRIP = 'GRANULAR GRIP'
    GS_50_WOOD_GRAIN = 'GS .50 WOOD GRAIN'
    GS_MAGNA_AKIMBO = 'GS MAGNA AKIMBO'
    HARKEN_OP_GRIP = 'HARKEN OP GRIP'
    HARROW_PALMREST_GRIP = 'HARROW PALMREST GRIP'
    HASTE_XV_GRIP_TAPE = 'HASTE XV GRIP TAPE'
    INTRUDER_GRIP = 'INTRUDER GRIP'
    IVANOV_ST_70_GRIP = 'IVANOV ST-70 GRIP'
    IVANOV_XT_35_STEADY_GRIP = 'IVANOV XT-35 STEADY GRIP'
    LACHMANN_TCG_10 = 'LACHMANN TCG-10'
    LM_CRONUS_GRIP = 'LM CRONUS GRIP'
    LMK64_GRIP = 'LMK64 GRIP'
    LOKIS_VEIL = "LOKI'S VEIL"
    MAGWELL_GRIP = "MAGWELL GRIP"
    MARAUDER_GRIP = 'MARAUDER GRIP'
    MARKSMAN_PALM_GRIP = 'MARKSMAN PALM GRIP'
    MOLTEN_ASSAULT_GRIP = 'MOLTEN ASSAULT GRIP'
    MORN_20_GRIP = 'MORN-20 GRIP'
    MTZ_AGGRESSOR_GRIP = 'MTZ AGGRESSOR GRIP'
    MTZ_FACTORY_REAR_GRIP = 'MTZ FACTORY REAR GRIP'
    NO_MODIFICATIONS = "NO MODIFICATIONS"
    NOUGHT_Z3_GRIP = 'NOUGHT-Z3 GRIP'
    PCS_90_ASSAULT_GRIP = "PCS-90 ASSAULT GRIP"
    PHANTOM_GRIP = 'PHANTOM GRIP'
    Q22_TACTICAL_GRIP = 'Q22 TACTICAL GRIP'
    RANGE_GRIP = "RANGE GRIP"
    RAZORLEAF_GRIP = 'RAZORLEAF GRIP'
    RB_BOREALIS_GRIP = 'RB BOREALIS GRIP'
    RB_CLAW_PSL_GRIP = 'RB CLAW-PSL GRIP'
    RB_PALM_SHELF_GRIP = 'RB PALM SHELF GRIP'
    RB_RAPIDSTRIKE_GRIP = 'RB RAPIDSTRIKE GRIP'
    RENETTI_WOOD_GRAIN_GRIP = 'RENETTI WOOD GRAIN GRIP'
    RETORT_90_GRIP_TAPE = 'RETORT 90 GRIP TAPE'
    RIVAL_ACE_GRIP = 'RIVAL ACE GRIP'
    RIVAL_CLUTCH_GRIP = 'RIVAL CLUTCH GRIP'
    RIVAL_G_5_SERIES_GRIP = 'RIVAL G-5 SERIES GRIP'
    RIVAL_VICE_ASSAULT_GRIP = 'RIVAL VICE ASSAULT GRIP'
    RMT_GRIP = 'RMT GRIP'
    S_GRIP_ZERO = 'S-GRIP ZERO'
    SA_CATION_GRIP = 'SA CATION GRIP'
    SA_FINESSE_GRIP = 'SA FINESSE GRIP'
    SA_ION = 'SA ION'
    SAKIN_RUBBER_GRIP = 'SAKIN RUBBER GRIP'
    SAKIN_ZX_GRIP = 'SAKIN ZX GRIP'
    SCHLAGER_FANG_GRIP = 'SCHLAGER FANG GRIP'
    SCHLAGER_MATCH_GRIP = 'SCHLAGER MATCH GRIP'
    SCHLAGER_SOLDIER_GRIP = 'SCHLAGER SOLDIER GRIP'
    SCHLAGER_VOID_GRIP = 'SCHLAGER VOID GRIP'
    SGT_GRIP = 'SGT GRIP'
    SIGURDS_FIST = "SIGURD'S FIST"
    SINGER_LR_GRIP = 'SINGER LR GRIP'
    SKULL_40 = 'SKULL-40'
    SO_RO_99_GRIP = 'SO RO-99 GRIP'
    STALWART_GRIP = 'STALWART GRIP'
    STALWART_GX = 'STALWART GX'
    STIP_40_GRIP = 'STIP-40 GRIP'
    STIP_66_GRIP = 'STIP-66 GRIP'
    STIPPLED_GRIP_COVER = 'STIPPLED GRIP COVER'
    STREAM_SK = 'STREAM-SK'
    STT88_GRIP = 'STT88 GRIP'
    SUPPORT_CP90_GRIP = 'SUPPORT CP90 GRIP'
    SUR_160 = 'SUR-160'
    TAC_HANDLER_GRIP = "TAC HANDLER GRIP"
    TACGRIP = 'TACGRIP'
    TACTICAL_GRIP_COVER = 'TACTICAL GRIP COVER'
    TACTICAL_GRIP_TAPE = 'TACTICAL GRIP TAPE'
    TOURNEY_TAC_GRIP = 'TOURNEY TAC GRIP'
    TRUE_TAC_GRIP = 'TRUE-TAC GRIP'
    TV_ERGO_GRIP = 'TV ERGO GRIP'
    TV_NOUGHT_GRIP = 'TV NOUGHT GRIP'
    TYRANNICAL_LX9_GRIP = 'TYRANNICAL LX9 GRIP'
    VARANUS_STEADY_GRIP = 'VARANUS STEADY GRIP'
    WSP_HARK_RUBBER_GRIP = 'WSP HARK RUBBER GRIP'
    WSP_TAC_20_GRIP = 'WSP TAC-20 GRIP'
    XRK_FIELD_GRIP = 'XRK FIELD GRIP'
    XRK_RESPONSE_GRIP = 'XRK RESPONSE GRIP'
    XRK_RUSH = 'XRK RUSH'
    XRK_SNIPER_PALMREST_GRIP = 'XRK SNIPER PALMREST GRIP'
    XRK_STALKER_FACTORY_GRIP = 'XRK STALKER FACTORY GRIP'
    XTEN_GRIP = 'XTEN GRIP'
    ZLR_COMBAT_GRIP = 'ZLR COMBAT GRIP'

class TriggerActions(Enum):
    # from https://game8.co/games/Modern-Warfare-3/archives/431912
    # used CHAT GPT to generate list
    ALIS_REGRET = "ALI'S REGRET"
    BASILISK_HT7 = "BASILISK HT-7"
    BRUEN_EXPRESS = "BRUEN EXPRESS"
    BRUEN_MG80_TRIGGER = "BRUEN MG80 TRIGGER"
    BRUEN_MG89_TRIGGER = "BRUEN MG89 TRIGGER"
    BRYSON_HTA = "BRYSON HTA"
    BRYSON_MATCH_GRADE = "BRYSON MATCH GRADE"
    BURST_FIRE_TRIGGER = "BURST-FIRE TRIGGER"
    DEX8_TRIGGER = "DEX8 TRIGGER"
    HARDSTANCE_BIPOD = "HARDSTANCE BIPOD"
    MAELSTROM_DUAL_TRIGGER = "MAELSTROM DUAL TRIGGER"
    NO_MODIFICATIONS = "NO MODIFICATIONS"
    ODINS_JUDGEMENT = "ODIN'S JUDGEMENT"
    P890_DOUBLE_ACTION = "P890 DOUBLE ACTION"
    PRECISION_TRIGGER = "PRECISION TRIGGER"
    RAPID_30_TRIGGER = "RAPID 30 TRIGGER"
    SA_COMPETITION_TRIGGER = "SA COMPETITION TRIGGER"
    SA_FIFTY_TRIGGER = "SA FIFTY TRIGGER"
    SA_HARE_TRIGGER = "SA HARE TRIGGER"
    SEMI_AUTO_TRIGGER = "SEMI-AUTO TRIGGER"
    ULLRS_FURY = "ULLR'S FURY"
    XRK_HEAVY_V3 = "XRK HEAVY V3"
    XRK_HEAVY_V4 = "XRK HEAVY V4"
    XRK_LIGHTNING_FIRE = "XRK LIGHTNING FIRE"
    XRK_TR9_TRIGGER = "XRK TR9 TRIGGER"
    XRK_V21_HEAVY_MATCH = "XRK V21 HEAVY MATCH"
    XRK_V6_MATCH = "XRK V6 MATCH"

class Magazines(Enum):
    # from https://game8.co/games/Modern-Warfare-3/archives/431912
    # used CHAT GPT to generate list
    FENNEC_DOUBLE_TAP = "FENNEC DOUBLE TAP MOD"
    FENNEC_MAG_45 = "FENNEC MAG 45"
    GEIST_SINGLE_TAP = "GEIST SINGLE-TAP MOD"
    MINIBAK_GRIP = "MINIBAK GRIP MAG"
    MX_PRO = "MX PRO MAG"
    NO_MODIFICATIONS = "NO MODIFICATIONS"
    ROUND_10 = "10 ROUND MAG"
    ROUND_100_556_BELT = "100 ROUND 556 BELT"
    ROUND_100_BELT = "100 ROUND BELT MAG"
    ROUND_100_BOX = "100 ROUND BOX MAG"
    ROUND_100_DRUM = "100 ROUND DRUM"
    ROUND_100_MAG = "100 ROUND MAG" #RAPP LMG
    ROUND_100 = "100 ROUND MAG"
    ROUND_12 = "12 ROUND MAG"
    ROUND_125_BELT = "125 ROUND BELT MAG"
    ROUND_13 = "13 ROUND MAG"
    ROUND_15 = "15 ROUND MAG"
    ROUND_15_MAGAZINE = "15 ROUND MAGAZINE"
    ROUND_150_BELT = "150 ROUND BELT"
    ROUND_150_DRUM = "150 ROUND DRUM"
    ROUND_150_BOX = "150-ROUND BOX MAGAZINE"
    ROUND_18 = "18 ROUND MAG"
    ROUND_20_DRUM = "20 ROUND DRUM"
    ROUND_20 = "20 ROUND MAG"
    ROUND_20_MAGAZINE = "20 ROUND MAGAZINE"
    ROUND_200_556_BELT = "200 ROUND 556 BELT"
    ROUND_200_BELT = "200 ROUND BELT"
    ROUND_200_BELT_MAG = "200 ROUND BELT MAG"
    ROUND_24 = "24 ROUND MAG"
    ROUND_25 = "25 ROUND MAG"
    ROUND_26 = "26 ROUND MAG"
    ROUND_30_DRUM = "30 ROUND DRUM"
    ROUND_30 = "30 ROUND MAG"
    ROUND_32 = "32 ROUND MAG"
    ROUND_33 = "33 ROUND MAG"
    ROUND_40_DRUM = "40 ROUND DRUM"
    ROUND_40 = "40 ROUND MAG"
    ROUND_42 = "42 ROUND MAG"
    ROUND_45 = "45 ROUND MAG"
    ROUND_45_DRUM = "45 ROUND DRUM"
    ROUND_48 = "48 ROUND MAG"
    ROUND_5 = "5 ROUND MAG"
    ROUND_5_MAGAZINE = "5 ROUND MAGAZINE"
    ROUND_50_762_BELT = "50 ROUND 762 BELT"
    ROUND_50_BELT_MAG = "50 ROUND BELT MAG"
    ROUND_50_DRUM = "50 ROUND DRUM"
    ROUND_50 = "50 ROUND MAG"
    ROUND_60_DRUM = "60 ROUND DRUM"
    ROUND_60 = "60 ROUND MAG"
    ROUND_7 = "7 ROUND MAG"
    ROUND_7_MAGAZINE = "7 ROUND MAGAZINE"
    ROUND_72_DRUM = "72 ROUND DRUM"
    ROUND_75_BELT = "75 ROUND BELT"
    ROUND_8_MAGAZINE = "8-ROUND MAGAZINE"
    ROUND_9 = "9 ROUND MAG"
    SHELL_12 = "12 SHELL MAG"
    SHELL_25_DRUM = "25 SHELL DRUM"
    SHELL_5 = "5 SHELL MAG"
    SINGLE_TAP = "SINGLE TAP MOD"
    STINGER_25 = "STINGER 25 ROUND MAGAZINE"

class Loaders(Enum):
    S40_RAPID_LOADER = "S40 RAPID LOADER"
    B_3ST_LOADER = "B-3ST LOADER"

class Wires(Enum):
    NO_MODIFICATIONS = "NO MODIFICATIONS"
    STRAND_16_CABLE = "16 STRAND CABLE"
    STRAND_28_CABLE = "28 STRAND CABLE"

class Rails(Enum):
    INTEGRATED_REFLEX_RAIL = "INTEGRATED REFLEX RAIL"
    GR33_LIGHT_RAIL = "GR33 LIGHT RAIL"
    NO_MODIFICATIONS = "NO MODIFICATIONS"

class AmmoTypes(Enum):
    # from https://game8.co/games/Modern-Warfare-3/archives/431912
    # used CHAT GPT to generate list, alphabetical order was done manually
    AET_ROUNDS_P_12_7X55MM = "12.7X55MM AET ROUNDS+P"
    AET_ROUNDS_500 = ".500 AET ROUNDS"
    AET_ROUNDS_9MM = "9MM AET ROUNDS"
    ARMOR_PIERCING_12_7X55MM = "12.7X55MM ARMOR PIERCING"
    ARMOR_PIERCING_277 = ".277 ARMOR PIERCING"
    ARMOR_PIERCING_300 = ".300 ARMOR PIERCING"
    ARMOR_PIERCING_308 = ".308 ARMOR PIERCING"
    ARMOR_PIERCING_4_6MM = "4.6MM ARMOR PIERCING"
    ARMOR_PIERCING_408 = ".408 ARMOR PIERCING"
    ARMOR_PIERCING_458 = ".458 ARMOR PIERCING"
    ARMOR_PIERCING_5_45 = "5.45 ARMOR PIERCING"
    ARMOR_PIERCING_5_56 = "5.56 ARMOR PIERCING"
    ARMOR_PIERCING_5_7X28MM = "5.7X28MM ARMOR PIERCING"
    ARMOR_PIERCING_5_8X42 = "5.8X42 ARMOR PIERCING"
    ARMOR_PIERCING_500 = ".500 ARMOR PIERCING"
    ARMOR_PIERCING_6_5MM = "6.5MM ARMOR PIERCING"
    ARMOR_PIERCING_6_8 = "6.8 ARMOR PIERCING"
    ARMOR_PIERCING_7_62X39MM = "7.62X39MM ARMOR PIERCING"
    ARMOR_PIERCING_7_62X51MM = "7.62X51MM ARMOR PIERCING"
    ARMOR_PIERCING_7_62X54MMR = "7.62X54MMR ARMOR PIERCING"
    ARMOR_PIERCING_9MM = "9MM ARMOR PIERCING"
    AUTO_AET_ROUNDS_45 = ".45 AUTO AET ROUNDS"
    AUTO_ARMOR_PIERCING_45 = ".45 AUTO ARMOR PIERCING"
    AUTO_FRANGIBLE_45 = ".45 AUTO FRANGIBLE"
    AUTO_HARDENED_ROUNDS_45 = ".45 AUTO HARDENED ROUNDS"
    AUTO_HIGH_GRAIN_ROUNDS_45 = ".45 AUTO HIGH GRAIN ROUNDS"
    AUTO_HOLLOWPOINT_45 = ".45 AUTO HOLLOWPOINT"
    AUTO_LOW_GRAIN_ROUNDS_45 = ".45 AUTO LOW GRAIN ROUNDS"
    AUTO_OVERPRESSURED_P_45 = ".45 AUTO OVERPRESSURED +P"
    BLACKOUT_HIGH_GRAIN_ROUNDS = "BLACKOUT HIGH GRAIN ROUNDS"
    BLACKOUT_LOW_GRAIN_ROUNDS = "BLACKOUT LOW GRAIN ROUNDS"
    BLACKOUT_MONO = "BLACKOUT MONO"
    BLACKOUT_ROUND_NOSE = "BLACKOUT ROUND NOSE"
    BLK_ARMOR_PIERCING_300 = ".300 BLK ARMOR PIERCING"
    BLK_FRANGIBLE_300 = ".300 BLK FRANGIBLE"
    BLK_HOLLOWPOINT_300 = ".300 BLK HOLLOWPOINT"
    BLK_OVERPRESSURED_P_300 = ".300 BLK OVERPRESSURED +P"
    BOLO_SHELLS = "BOLO SHELLS"
    CAL_ARMOR_PIERCING_50 = ".50 CAL ARMOR PIERCING"
    CAL_EXPLOSIVE_50 = ".50 CAL EXPLOSIVE"
    CAL_FRANGIBLE_50 = ".50 CAL FRANGIBLE"
    CAL_HIGH_GRAIN_ROUNDS_50 = ".50 CAL HIGH GRAIN ROUNDS"
    CAL_HIGH_VELOCITY_50 = ".50 CAL HIGH VELOCITY"
    CAL_INCENDIARY_50 = ".50 CAL INCENDIARY"
    CAL_LOW_GRAIN_ROUNDS_50 = ".50 CAL LOW GRAIN ROUNDS"
    CAL_MONO_50 = ".50 CAL MONO"
    CAL_SPIRE_POINT_ROUNDS_50 = ".50 CAL SPIRE POINT ROUNDS"
    COMPOSITE_6_8 = "6.8 COMPOSITE"
    EXPLOSIVE_408 = ".408 EXPLOSIVE"
    FRANGIBLE_12_7X55MM = "12.7X55MM FRANGIBLE"    
    FRANGIBLE_277 = ".277 FRANGIBLE"
    FRANGIBLE_300 = ".300 FRANGIBLE"
    FRANGIBLE_308 = ".308 FRANGIBLE"
    FRANGIBLE_408 = ".408 FRANGIBLE"
    FRANGIBLE_4_6MM = "4.6MM FRANGIBLE"
    FRANGIBLE_458 = ".458 FRANGIBLE"
    FRANGIBLE_5_45 = "5.45 FRANGIBLE"
    FRANGIBLE_5_56 = "5.56 FRANGIBLE"
    FRANGIBLE_5_7X28MM = "5.7X28MM FRANGIBLE"
    FRANGIBLE_5_8X42 = "5.8X42 FRANGIBLE"
    FRANGIBLE_500 = ".500 FRANGIBLE"
    FRANGIBLE_6_5MM = "6.5MM FRANGIBLE"
    FRANGIBLE_6_8 = "6.8 FRANGIBLE"
    FRANGIBLE_7_62X39MM = "7.62X39MM FRANGIBLE"
    FRANGIBLE_7_62X51MM = "7.62X51MM FRANGIBLE"
    FRANGIBLE_7_62X54MMR = "7.62X54MMR FRANGIBLE"
    FRANGIBLE_9MM = "9MM FRANGIBLE"
    GAUGE_BALL_410 = ".410 GAUGE BALL"
    GAUGE_DRAGONS_BREATH_12 = "12 GAUGE DRAGON'S BREATH"
    GAUGE_EXPLOSIVE_12 = "12 GAUGE EXPLOSIVE"
    GAUGE_INCENDIARY_410 = ".410 GAUGE INCENDIARY"
    GAUGE_SLUG_12 = "12 GAUGE SLUG"
    GAUGE_SLUG_SHELLS_410 = ".410 GAUGE SLUG SHELLS"
    GVT_ARMOR_PIERCING_45 = ".45 GVT ARMOR PIERCING"
    GVT_FRANGIBLE_45 = ".45 GVT FRANGIBLE"
    GVT_HIGH_VELOCITY_45 = ".45 GVT HIGH VELOCITY"
    GVT_HOLLOWPOINT_45 = ".45 GVT HOLLOWPOINT"
    GVT_INCENDIARY_45 = ".45 GVT INCENDIARY"
    GVT_OVERPRESSURED_P_45 = ".45 GVT OVERPRESSURED +P"
    HARDENED_ROUNDS_12_7X55MM = "12.7X55MM HARDENED ROUNDS"
    HARDENED_ROUNDS_500 = ".500 HARDENED ROUNDS"
    HARDENED_ROUNDS_9MM = "9MM HARDENED ROUNDS"
    HIGH_GRAIN_ROUNDS_12_7X55MM = "12.7X55MM HIGH GRAIN ROUNDS"
    HIGH_GRAIN_ROUNDS_277 = ".277 HIGH GRAIN ROUNDS"
    HIGH_GRAIN_ROUNDS_5_45 = "5.45 HIGH GRAIN ROUNDS"
    HIGH_GRAIN_ROUNDS_5_8X42 = "5.8X42 HIGH GRAIN ROUNDS"
    HIGH_GRAIN_ROUNDS_500 = ".500 HIGH GRAIN ROUNDS"
    HIGH_GRAIN_ROUNDS_7_62X39MM = "7.62X39MM HIGH GRAIN ROUNDS"
    HIGH_GRAIN_ROUNDS_7_62X51MM = "7.62X51MM HIGH GRAIN ROUNDS"
    HIGH_GRAIN_ROUNDS_7_62X54MMR = "7.62X54MMR HIGH GRAIN ROUNDS"
    HIGH_GRAIN_ROUNDS_9MM = "9MM HIGH GRAIN ROUNDS"
    HIGH_VELOCITY_277 = ".277 HIGH VELOCITY"
    HIGH_VELOCITY_300 = ".300 HIGH VELOCITY"
    HIGH_VELOCITY_308 = ".308 HIGH VELOCITY"
    HIGH_VELOCITY_408 = ".408 HIGH VELOCITY"
    HIGH_VELOCITY_458 = ".458 HIGH VELOCITY"
    HIGH_VELOCITY_5_45 = "5.45 HIGH VELOCITY"
    HIGH_VELOCITY_5_56 = "5.56 HIGH VELOCITY"
    HIGH_VELOCITY_5_8X42 = "5.8X42 HIGH VELOCITY"
    HIGH_VELOCITY_6_5MM = "6.5MM HIGH VELOCITY"
    HIGH_VELOCITY_6_8 = "6.8 HIGH VELOCITY"
    HIGH_VELOCITY_7_62X39MM = "7.62X39MM HIGH VELOCITY"
    HIGH_VELOCITY_7_62X51MM = "7.62X51MM HIGH VELOCITY"
    HIGH_VELOCITY_7_62X54MMR = "7.62X54MMR HIGH VELOCITY"
    HIGH_VELOCITY_9MM = "9MM HIGH VELOCITY"
    HOLLOWPOINT_12_7X55MM = "12.7X55MM HOLLOWPOINT"
    HOLLOWPOINT_277 = ".277 HOLLOWPOINT"
    HOLLOWPOINT_300 = ".300 HOLLOWPOINT"
    HOLLOWPOINT_308 = ".308 HOLLOWPOINT"
    HOLLOWPOINT_4_6MM = "4.6MM HOLLOWPOINT"
    HOLLOWPOINT_408 = ".408 HOLLOWPOINT"
    HOLLOWPOINT_458 = ".458 HOLLOWPOINT"
    HOLLOWPOINT_5_45 = "5.45 HOLLOWPOINT"
    HOLLOWPOINT_5_56 = "5.56 HOLLOWPOINT"
    HOLLOWPOINT_5_7X28MM = "5.7X28MM HOLLOWPOINT"
    HOLLOWPOINT_5_8X42 = "5.8X42 HOLLOWPOINT"
    HOLLOWPOINT_500 = ".500 HOLLOWPOINT"
    HOLLOWPOINT_6_5MM = "6.5MM HOLLOWPOINT"
    HOLLOWPOINT_6_8 = "6.8 HOLLOWPOINT"
    HOLLOWPOINT_7_62X39MM = "7.62X39MM HOLLOWPOINT"
    HOLLOWPOINT_7_62X51MM = "7.62X51MM HOLLOWPOINT"
    HOLLOWPOINT_7_62X54MMR = "7.62X54MMR HOLLOWPOINT"
    HOLLOWPOINT_9MM = "9MM HOLLOWPOINT"
    HUNTSMAN_ARMOR_PIERCING_450 = "450 HUNTSMAN ARMOR PIERCING"
    HUNTSMAN_FRANGIBLE_450 = "450 HUNTSMAN FRANGIBLE"
    HUNTSMAN_HIGH_GRAIN_ROUNDS_450 = "450 HUNTSMAN HIGH GRAIN ROUNDS"
    HUNTSMAN_HIGH_VELOCITY_450 = "450 HUNTSMAN HIGH VELOCITY"
    HUNTSMAN_HOLLOWPOINT_450 = "450 HUNTSMAN HOLLOWPOINT"
    HUNTSMAN_LOW_GRAIN_ROUNDS_450 = "450 HUNTSMAN LOW GRAIN ROUNDS"
    HUNTSMAN_MONO_450 = "450 HUNTSMAN MONO"
    HUNTSMAN_OVERPRESSURED_P_450 = "450 HUNTSMAN OVERPRESSURED +P"
    HUNTSMAN_ROUND_NOSE_450 = "450 HUNTSMAN ROUND NOSE"
    HUNTSMAN_TRACER_450 = "450 HUNTSMAN TRACER"
    INCENDIARY_277 = ".277 INCENDIARY"
    INCENDIARY_300 = ".300 INCENDIARY"
    INCENDIARY_308 = ".308 INCENDIARY"
    INCENDIARY_408 = ".408 INCENDIARY"
    INCENDIARY_5_56 = "5.56 INCENDIARY"
    INCENDIARY_5_8X42 = "5.8X42 INCENDIARY"
    INCENDIARY_6_5MM = "6.5MM INCENDIARY"
    INCENDIARY_6_8 = "6.8 INCENDIARY"
    INCENDIARY_7_62X39MM = "7.62X39MM INCENDIARY"
    INCENDIARY_7_62X51MM = "7.62X51MM INCENDIARY"
    INCENDIARY_7_62X54MMR = "7.62X54MMR INCENDIARY"
    LOW_GRAIN_ROUNDS_12_7X55MM = "12.7X55MM LOW GRAIN ROUNDS"
    LOW_GRAIN_ROUNDS_277 = ".277 LOW GRAIN ROUNDS"
    LOW_GRAIN_ROUNDS_5_45 = "5.45 LOW GRAIN ROUNDS"
    LOW_GRAIN_ROUNDS_5_8X42 = "5.8X42 LOW GRAIN ROUNDS"
    LOW_GRAIN_ROUNDS_500 = ".500 LOW GRAIN ROUNDS"
    LOW_GRAIN_ROUNDS_7_62X39MM = "7.62X39MM LOW GRAIN ROUNDS"
    LOW_GRAIN_ROUNDS_7_62X51MM = "7.62X51MM LOW GRAIN ROUNDS"
    LOW_GRAIN_ROUNDS_7_62X54MMR = "7.62X54MMR LOW GRAIN ROUNDS"
    LOW_GRAIN_ROUNDS_9MM = "9MM LOW GRAIN ROUNDS"
    MAG_ARMOR_PIERCING_300 = ".300 MAG ARMOR PIERCING"
    MAG_ARMOR_PIERCING_338 = ".338 MAG ARMOR PIERCING"
    MAG_EXPLOSIVE_300 = ".300 MAG EXPLOSIVE"
    MAG_FRANGIBLE_300 = ".300 MAG FRANGIBLE"
    MAG_FRANGIBLE_338 = ".338 MAG FRANGIBLE"
    MAG_HIGH_VELOCITY_300 = ".300 MAG HIGH VELOCITY"
    MAG_HIGH_VELOCITY_338 = ".338 MAG HIGH VELOCITY"
    MAG_HOLLOWPOINT_300 = ".300 MAG HOLLOWPOINT"
    MAG_HOLLOWPOINT_338 = ".338 MAG HOLLOWPOINT"
    MAG_INCENDIARY_300 = ".300 MAG INCENDIARY"
    MAG_INCENDIARY_338 = ".338 MAG INCENDIARY"
    MAG_OVERPRESSURED_P_300 = ".300 MAG OVERPRESSURED +P"
    MAG_OVERPRESSURED_P_338 = ".338 MAG OVERPRESSURED +P"
    MAG_ROUND_NOSE_338 = ".338 MAG ROUND NOSE"
    MAGNUM_ARMOR_PIERCING_338 = ".338 MAGNUM ARMOR PIERCING"
    MAGNUM_FRANGIBLE_338 = ".338 MAGNUM FRANGIBLE"
    MAGNUM_HIGH_GRAIN_ROUNDS_338 = ".338 MAGNUM HIGH GRAIN ROUNDS"
    MAGNUM_HOLLOWPOINT_338 = ".338 MAGNUM HOLLOWPOINT"
    MAGNUM_INCENDIARY_338 = ".338 MAGNUM INCENDIARY"
    MAGNUM_LOW_GRAIN_ROUNDS_338 = ".338 MAGNUM LOW GRAIN ROUNDS"
    MAGNUM_MONO_338 = ".338 MAGNUM MONO"
    MAGNUM_OVERPRESSURED_P_338 = ".338 MAGNUM OVERPRESSURED+P"
    MAGNUM_ROUND_NOSE_338 = ".338 MAGNUM ROUND NOSE"
    MAGNUM_SPIRE_POINT_338 = ".338 MAGNUM SPIRE POINT"
    MONO_277 = ".277 MONO"
    MONO_5_8X42 = "5.8X42 MONO"
    MONO_7_62X39MM = "7.62X39MM MONO"
    MONO_7_62X51MM = "7.62X51MM MONO"
    MONO_7_62X54MMR = "7.62X54MMR MONO"
    NATO_HIGH_GRAIN_ROUNDS_5_56 = "5.56 NATO HIGH GRAIN ROUNDS"
    NATO_LOW_GRAIN_ROUNDS_5_56 = "5.56 NATO LOW GRAIN ROUNDS"
    NATO_MONO_5_56 = "5.56 NATO MONO"
    NATO_OVERPRESSURED_P_5_56 = "5.56 NATO OVERPRESSURED +P"
    NATO_ROUND_NOSE_5_56 = "5.56 NATO ROUND NOSE"
    NATO_TRACER_5_56 = "5.56 NATO TRACER"
    NO_MODIFICATIONS = "NO MODIFICATIONS"
    OVERPRESSURED_P_12_7X55MM = "12.7X55MM OVERPRESSURED +P"
    OVERPRESSURED_P_277 = ".277 OVERPRESSURE+P"
    OVERPRESSURED_P_300 = ".300 OVERPRESSURED +P"
    OVERPRESSURED_P_308 = ".308 OVERPRESSURED +P"
    OVERPRESSURED_P_4_6MM = "4.6MM OVERPRESSURED +P"
    OVERPRESSURED_P_408 = ".408 OVERPRESSURE +P"
    OVERPRESSURED_P_458 = ".458 OVERPRESSURED +P"
    OVERPRESSURED_P_5_45 = "5.45 OVERPRESSURED +P"
    OVERPRESSURED_P_5_7X28MM = "5.7X28MM OVERPRESSURED +P"
    OVERPRESSURED_P_5_56 = "5.56 OVERPRESSURED +P"
    OVERPRESSURED_P_5_8X42 = "5.8X42 OVERPRESSURED +P"
    OVERPRESSURED_P_500 = ".500 OVERPRESSURED +P"
    OVERPRESSURED_P_6_5MM = "6.5MM OVERPRESSURED +P"
    OVERPRESSURED_P_6_8 = "6.8 OVERPRESSURED +P"
    OVERPRESSURED_P_7_62X39MM = "7.62X39MM OVERPRESSURED +P"
    OVERPRESSURED_P_7_62X51MM = "7.62X51MM OVERPRESSURED +P"
    OVERPRESSURED_P_7_62X54MMR = "7.62X54MMR OVERPRESSURED +P"
    OVERPRESSURED_P_9MM = "9MM OVERPRESSURED +P"
    PACE_HIGH_GRAIN_ROUNDS_408 = ".408 PACE HIGH GRAIN ROUNDS"
    PACE_LOW_GRAIN_ROUNDS_408 = ".408 PACE LOW GRAIN ROUNDS"
    PACE_MONO_408 = ".408 PACE MONO"
    PACE_ROUND_NOSE_408 = ".408 PACE ROUND NOSE"
    PISTOL_ARMOR_PIERCING_50 = ".50 PISTOL ARMOR PIERCING"
    PISTOL_FRANGIBLE_50 = ".50 PISTOL FRANGIBLE"
    PISTOL_HOLLOWPOINT_50 = ".50 PISTOL HOLLOWPOINT"
    PISTOL_OVERPRESSURED_P_50 = ".50 PISTOL OVERPRESSURED +P"
    ROUND_NOSE_277 = ".277 ROUND NOSE"
    ROUND_NOSE_5_8X42 = "5.8X42 ROUND NOSE"
    ROUND_NOSE_7_62X39MM = "7.62X39MM ROUND NOSE"
    ROUND_NOSE_7_62X51MM = "7.62X51MM ROUND NOSE"
    ROUND_NOSE_7_62X54MMR = "7.62X54MMR ROUND NOSE"
    SNAKESHOT_12_7X55MM = "12.7X55MM SNAKE SHOT"
    SNAKESHOT_500 = ".500 SNAKESHOT"
    SUB_AP_9MM = "9MM SUB AP"
    SUB_FR_9MM = "9MM SUB FR"
    SUB_HP_9MM = "9MM SUB HP"
    SUB_OP_9MM = "9MM SUB OP"
    TRACER_277 = ".277 TRACER"
    TRACER_5_8X42 = "5.8X42 TRACER"
    TRACER_7_62X54MMR = "7.62X54MMR TRACER"
    WRATH_ARMOR_PIERCING_6_8 = "6.8 WRATH ARMOR PIERCING"
    WRATH_FRANGIBLE_6_8 = "6.8 WRATH FRANGIBLE"
    WRATH_HIGH_GRAIN_ROUNDS_6_8 = "6.8 WRATH HIGH GRAIN ROUNDS"
    WRATH_HIGH_VELOCITY_6_8 = "6.8 WRATH HIGH VELOCITY"
    WRATH_HOLLOWPOINT_6_8 = "6.8 WRATH HOLLOWPOINT"
    WRATH_INCENDIARY_6_8 = "6.8 WRATH INCENDIARY"
    WRATH_LOW_GRAIN_ROUNDS_6_8 = "6.8 WRATH LOW GRAIN ROUNDS"
    WRATH_MONO_6_8 = "6.8 WRATH MONO"
    WRATH_OVERPRESSURED_P_6_8 = "6.8 WRATH OVERPRESSURED +P"
    WRATH_ROUND_NOSE_6_8 = "6.8 WRATH ROUND NOSE"
    WRATH_SPIRE_POINT_ROUNDS_6_8 = "6.8 WRATH SPIRE POINT ROUNDS"
    WRATH_TRACER_6_8 = "6.8 WRATH TRACER"

class Underbarrels(Enum):
    AGENT_GRIP = "AGENT GRIP"
    BIPOD_V9_GRIP = "BIPOD V9 GRIP"
    BO52_GRIP = "BO52 GRIP"
    BRUEN_BASTION_ANGLED_GRIP = "BRUEN BASTION ANGLED GRIP"
    BRUEN_HEAVY_BIPOD = "BRUEN HEAVY BIPOD"
    BRUEN_HEAVY_SUPPORT_GRIP = "BRUEN HEAVY SUPPORT GRIP"
    BRUEN_MK9_BIPOD = "BRUEN MK9 BIPOD"
    BRUEN_PIVOT_VERTICAL_GRIP = "BRUEN PIVOT VERTICAL GRIP"
    BRUEN_SYNC_SHOT_GRIP = "BRUEN SYNC SHOT GRIP"
    BRUEN_TACTICAL_VERTICAL_GRIP = "BRUEN TACTICAL VERTICAL GRIP"
    BRUEN_TILT_GRIP = "BRUEN TILT GRIP"
    BRUEN_WARRIOR_GRIP = "BRUEN WARRIOR GRIP"
    BRUEN_WARRIOR_LMG = "BRUEN WARRIOR LMG"
    BURROW_500_DRILL_CHARGE = "BURROW 500 DRILL CHARGE"
    CHEWK_ANGLED_GRIP = "CHEWK ANGLED GRIP"
    COMMANDO_FOREGRIP = "COMMANDO FOREGRIP"
    CORE_BP2 = "CORE BP2"
    CORNERSTONE_BIPOD = "CORNERSTONE BIPOD"
    CORVUS_MASTERKEY = "CORVUS MASTERKEY"
    CORVUS_TORCH = "CORVUS TORCH"
    CRONEN_GROOVESHOT_GRIP = "CRONEN GROOVESHOT GRIP"
    CRONEN_WL55 = "CRONEN WL55"
    DEMO_CLEANSHOT_40 = "DEMO CLEANSHOT 40"
    DEMO_FIRM_GRIP = "DEMO FIRM GRIP"
    DEMO_IMP_44_GRIP = "DEMO IMP-44 GRIP"
    DEMO_NARROW_GRIP = "DEMO NARROW GRIP"
    DI_GRIP_4p5 = "DI-GRIP 4.5"
    DM_PROTO_GRIP = "DM PHOTO GRIP"
    DR_6_HANDSTOP = "DR-6 HANDSTOP"
    EDGE_47_GRIP = "EDGE-47 GRIP"
    EXF_BACKDRAFT_GRIP = "EXF BACKDRAFT GRIP"
    FR_AVANCER_BIPOD = "FR AVANCER BIPOD"
    FTAC_MSP_98_HANDSTOP = "FTAC MSP-98 HANDSTOP"
    FTAC_RIPPER_56 = "FTAC RIPPER 56"
    FTAC_RS_9_STEALTH_ANGLED_GRIP = "FTAC RS-9 STEALTH ANGLED GRIP"
    FTAC_SP_10_ANGLED_GRIP = "FTAC SP-10 ANGLED GRIP"
    FTAC_TIGER_GRIP = "FTAC TIGER GRIP"
    FSS_SHARKFIN_90 = "FSS SHARKFIN 90"
    HELLSCREAM_40MM = "HELLSCREAM 40MM"
    HELLSCREAM_40MM_DRILL = "HELLSCREAM 40MM DRILL"
    HEX_40_GRIP = "HEX-40 GRIP"
    HOLGER_VERTICAL_GRIP = "HOLGER VERTICAL GRIP"
    HOUND_9G_GRIP = "HOUND-9G GRIP"
    JAK_LIMB_RIPPER = "JAK LIMB RIPPER"
    JAK_PURIFIER = "JAK PURIFIER"
    KL40_M2 = "KL40-M2"
    KL40_M2_DRILL = "KL40-M2 DRILL"
    KIMURA_RYN_03_VERTICAL_GRIP = "KIMURA RYN-03 VERTICAL GRIP"
    KIMURA_SERAPHIC_VERTICAL_GRIP = "KIMURA SERAPHIC VERTICAL GRIP"
    LEVEL_AIM_BIPOD = "LEVEL AIM BIPOD"
    LOCKGRIP_PRECISION_40 = "LOCKGRIP PRECISION-40"
    MERC_FOREGRIP = "MERC FOREGRIP"
    NO_MODIFICATIONS = "NO MODIFICATIONS"
    OP_X9_FOREGRIP = "OP-X9 FOREGRIP"
    OPERATOR_FOREGRIP = "OPERATOR FOREGRIP"
    PHASE_3_GRIP = "PHASE-3 GRIP"
    PULEMYOT_BIPOD = "PULEMYOT BIPOD"
    RAAL_BIPOD = "RAAL BIPOD"
    REBEL_HX = "REBEL-HX"
    RPK_BIPOD = "RPK BIPOD"
    S40_H_GRIP = "S40-H GRIP"
    SA_SIDE_GRIP = "SA SIDE GRIP"
    SAKIN_SIDE_GRIP = "SAKIN SIDE GRIP"
    SCHLAGER_TANGO = "SCHLAGER TANGO"
    SL_SKELETAL_VERTICAL_GRIP = "SL SKELETAL VERTICAL GRIP"
    SOSHKI = "SOSHKI"
    SPW_40MM_DRILL = "SPW 40MM DRILL"
    SPW_40MM_HE = "SPW 40MM HE"
    TAQ_EVOLVERE_LMG = "TAQ EVOLVERE LMG"
    TL40_DRILL = "TL40 DRILL"
    TL40_FIRE_DRAKE = "TL40 FIRE DRAKE"
    TTL_GS_40 = "TTL GS 40"
    TV_WRECKER_GRIP = "TV WRECKER GRIP"
    VX_PINEAPPLE = "VX PINEAPPLE"
    WEDGE_GRIP = "WEDGE GRIP"
    WSP_LIBERATOR_INTEGRATED_FOREGRIP = "WSP LIBERATOR INTEGRATED FOREGRIP"
    WSP_VENOM_GRIP = "WSP VENOM GRIP"
    XTEN_DROP_GRIP = "XTEN DROP GRIP"
    XTEN_GRAVEDIGGER = "XTEN GRAVEDIGGER"
    XTEN_NEXUS_GRIP = "XTEN NEXUS GRIP"
    XTEN_PHANTOM_5_HANDSTOP = "XTEN PHANTOM-5 HANDSTOP"
    XTEN_STABLE_SHOT = "XTEN STABLE SHOT"
    XTEN_TX_12_HANDSTOP = "XTEN TX-12 HANDSTOP"
    XRK_BOWBREAKER_GRIP = "XRK BOWBREAKER GRIP"
    XRK_DUNE_GRIP = "XRK DUNE GRIP"
    XRK_EDGE_BW_4_HANDSTOP = "XRK EDGE BW-4 HANDSTOP"

class CarryHandles(Enum):
    # added for FJX IMPERIUM Sniper Rifle
    FIELD_WRAPPED_HANDLE = "FIELD-WRAPPED HANDLE"
    KEYSTONE_HANDLE = "KEYSTONE HANDLE"
    NO_MODIFICATIONS = "NO MODIFICATIONS"

class ConversionKits(Enum):
    BROODMOTHER_45_KIT = "BROODMOTHER .45 KIT"
    FULL_AUTO_CARBINE_CONVERSION = "FULL-AUTO CARBINE CONVERSION"
    JAK_ANNIHILATOR_BULLPUP_KIT = "JAK ANNIHILATOR BULLPUP KIT"
    JAK_BACKSAW_KIT = "JAK BACKSAW KIT"
    JAK_BEHOLDER_RIFLE_KIT = "JAK BEHOLDER RIFLE KIT"
    JAK_BURNOUT_KIT = "JAK BURNOUT KIT"
    JAK_ETTIN_DOUBLE_BARREL = "JAK ETTIN DOUBLE BARREL"
    JAK_FEROCITY_CARBINE_KIT = "JAK FEROCITY CARBINE KIT"
    JAK_HEADHUNTER_CARBINE_CONVERSION = "JAK HEADHUNTER CARBINE CONVERSION"
    JAK_HERETIC_CARBINE_KIT = "JAK HERETIC CARBINE KIT"
    JAK_MAGLIFT_KIT = "JAK MAGLIFT KIT"
    JAK_NIGHTSHADE_RIFLE_KIT = "JAK NIGHTSHADE RIFLE KIT"
    JAK_OUTLAW_277_KIT = "JAK OUTLAW-277 KIT"
    JAK_RAVEN_KIT = "JAK RAVEN KIT"
    JAK_SIGNAL_BURST = "JAK SIGNAL BURST"
    JAK_THUNDER_LMG_KIT = "JAK THUNDER LMG KIT"
    JAK_TYRANT_762_KIT = "JAK TYRANT 762 KIT"
    MCW_6_8_FULL_AUTO_CONVERSION = "MCW 6.8 FULL-AUTO CONVERSION"
    WSP_AKIMBO_BRACE_STOCK = "WSP AKIMBO BRACE STOCK"
    XRK_IP_V2_CONVERSION_KIT = "XRK IP-V2 CONVERSION KIT"



class Attachments(Enum):
    MUZZLES = Muzzles
    BARRELS = Barrels
    ARMS = Arms
    LASERS = Lasers
    OPTICS = Optics
    STOCKS = Stocks
    COMBS = Combs
    GUARDS = Guards
    BOLTS = Bolts
    LEVERS = Levers
    REAR_GRIPS = RearGrips
    TRIGGER_ACTIONS = TriggerActions
    MAGAZINES = Magazines
    LOADERS = Loaders
    WIRES = Wires
    RAILS = Rails
    AMMO_TYPES = AmmoTypes
    UNDERBARRELS = Underbarrels
    CARRY_HANDLES = CarryHandles
    CONVERSION_KITS = ConversionKits